In [37]:
import pandas as pd
emp= {"name":["Ankit","Rahul","Priya"],"gender":["Male","Male","Female"], "email":["ankit@gmail.com","rahul@gmail.com","priya@gmail.com"] }
df = pd.DataFrame(emp)
df

    name  gender            email
0  Ankit    Male  ankit@gmail.com
1  Rahul    Male  rahul@gmail.com
2  Priya  Female  priya@gmail.com

In [10]:
#pandas #dataframe #how to create #iloc #loc #filter data
fc = (df_emp['name']=='Ankit')
#df_emp[fc]
df.loc[fc , ['gender']]

0    Male
Name: gender, dtype: object

In [16]:
df.index  = [0,1,2]
df

    name  gender            email
0  Ankit    Male  ankit@gmail.com
1  Rahul    Male  rahul@gmail.com
2  Priya  Female  priya@gmail.com

In [19]:
#df[fc]
df.loc[fc]

    name gender            email
0  Ankit   Male  ankit@gmail.com

In [21]:
df.columns

Index(['name', 'gender', 'email'], dtype='object')

In [31]:
df.columns = ['emp','gender','emp_email' ]
df

     emp  gender        emp_email
0  Ankit    Male  ankit@gmail.com
1  Rahul    Male  rahul@gmail.com
2  Priya  Female  priya@gmail.com

In [27]:
df.rename(columns = {'emp_name':'name', 'emp_email':'email'},inplace=True)
df

    name  gender            email
0  Ankit    Male  ankit@gmail.com
1  Rahul    Male  rahul@gmail.com
2  Priya  Female  priya@gmail.com

In [35]:
df.loc[0] = ['Ankitt','Male','ankitt@gmail.com']
df

      emp  gender         emp_email
0  Ankitt    Male  ankitt@gmail.com
1   Rahul    Male   rahul@gmail.com
2   Priya  Female   priya@gmail.com

In [39]:
df.loc[0] = ['Ankitt','Male','ankitt@gmail.com']

In [46]:
df.loc[0,['name','email']] = ['Ankit','ankit@gmail.com']

In [47]:
df

    name  gender            email
0  Ankit    Male  ankit@gmail.com
1  Rahul    Male  rahul@gmail.com
2  Priya  Female  priya@gmail.com

In [51]:
fc = (df['gender'] == 'Male')
df.loc[fc,'gender'] = 'Female'

In [52]:
df

    name  gender            email
0  Ankit  Female  ankit@gmail.com
1  Rahul  Female  rahul@gmail.com
2  Priya  Female  priya@gmail.com

In [57]:
#fc = (df['gender'] == 'Male')
df.loc[fc,'gender'] = 'Male'

0    female
1    female
Name: gender, dtype: object

In [58]:
df

    name  gender            email
0  Ankit  female  ankit@gmail.com
1  Rahul  female  rahul@gmail.com
2  Priya  female  priya@gmail.com

In [55]:
df.iloc[:,1] = 'female'

In [56]:
df

    name  gender            email
0  Ankit  female  ankit@gmail.com
1  Rahul  female  rahul@gmail.com
2  Priya  female  priya@gmail.com

In [61]:
df['gender'].apply(len)

0    6
1    6
2    6
Name: gender, dtype: int64

In [69]:
def update_email(inputval):
    return inputval.upper()

In [63]:
df['email'].apply(update_email)

0    ANKIT@GMAIL.COM
1    RAHUL@GMAIL.COM
2    PRIYA@GMAIL.COM
Name: email, dtype: object

In [65]:
df['email'] = df['email'].apply(update_email)

In [66]:
df

    name  gender            email
0  Ankit  female  ANKIT@GMAIL.COM
1  Rahul  female  RAHUL@GMAIL.COM
2  Priya  female  PRIYA@GMAIL.COM

In [70]:
df.applymap(update_email)

    name  gender            email
0  ANKIT  FEMALE  ANKIT@GMAIL.COM
1  RAHUL  FEMALE  RAHUL@GMAIL.COM
2  PRIYA  FEMALE  PRIYA@GMAIL.COM

In [71]:
df

    name  gender            email
0  Ankit  female  ANKIT@GMAIL.COM
1  Rahul  female  RAHUL@GMAIL.COM
2  Priya  female  PRIYA@GMAIL.COM

In [79]:
df['name'].str.lower()

0    ankit
1    rahul
2    priya
Name: name, dtype: object

In [84]:
df['name'] = df['name'].str.startswith('a')

In [86]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      bool
 1   gender  3 non-null      object
 2   email   3 non-null      object
dtypes: bool(1), object(2)
memory usage: 183.0+ bytes

In [87]:
df

    name  gender            email
0   True  female  ANKIT@GMAIL.COM
1  False  female  RAHUL@GMAIL.COM
2  False  female  PRIYA@GMAIL.COM

In [88]:
emp= {"name":["Ankit","Rahul","Priya"],"gender":["Male","Male","Female"], "email":["ankit@gmail.com","rahul@gmail.com","priya@gmail.com"] }
df = pd.DataFrame(emp)
df

    name  gender            email
0  Ankit    Male  ankit@gmail.com
1  Rahul    Male  rahul@gmail.com
2  Priya  Female  priya@gmail.com

In [89]:
df['salary'] = 10000
df

    name  gender            email  salary
0  Ankit    Male  ankit@gmail.com   10000
1  Rahul    Male  rahul@gmail.com   10000
2  Priya  Female  priya@gmail.com   10000

In [90]:
df['name_gender'] = df['name'] + ' ' + df['gender']

In [91]:
df

    name  gender            email  salary   name_gender
0  Ankit    Male  ankit@gmail.com   10000    Ankit Male
1  Rahul    Male  rahul@gmail.com   10000    Rahul Male
2  Priya  Female  priya@gmail.com   10000  Priya Female

In [92]:
df['salary'] = 20000
df

    name  gender            email  salary   name_gender
0  Ankit    Male  ankit@gmail.com   20000    Ankit Male
1  Rahul    Male  rahul@gmail.com   20000    Rahul Male
2  Priya  Female  priya@gmail.com   20000  Priya Female

In [93]:
df.loc[(df['name']=='Ankit') , 'salary'] = 5000

In [98]:
df

    name  gender            email  salary   name_gender  salary1
0  Ankit    Male  ankit@gmail.com    5000    Ankit Male     5000
1  Rahul    Male  rahul@gmail.com    6000    Rahul Male     6000
2  Priya  Female  priya@gmail.com    7000  Priya Female     7000

In [97]:
df['salary1'] = [5000,6000,7000]

In [102]:
#delete rows
#df.drop(index = 0 , inplace=True)
df.drop(index = 0 )

    name  gender            email  salary   name_gender  salary1
1  Rahul    Male  rahul@gmail.com    6000    Rahul Male     6000
2  Priya  Female  priya@gmail.com    7000  Priya Female     7000

In [105]:
fc = (df['salary'] >= 6000)
fc

0    False
1     True
2     True
Name: salary, dtype: bool

In [110]:
df.drop(index = df[fc].index )

    name gender            email  salary name_gender  salary1
0  Ankit   Male  ankit@gmail.com    5000  Ankit Male     5000

In [112]:
df[fc].index

Index([1, 2], dtype='int64')

In [113]:
df

    name  gender            email  salary   name_gender  salary1
0  Ankit    Male  ankit@gmail.com    5000    Ankit Male     5000
1  Rahul    Male  rahul@gmail.com    6000    Rahul Male     6000
2  Priya  Female  priya@gmail.com    7000  Priya Female     7000

In [115]:
#delete a column
df.drop(columns='salary1')

    name  gender            email  salary   name_gender
0  Ankit    Male  ankit@gmail.com    5000    Ankit Male
1  Rahul    Male  rahul@gmail.com    6000    Rahul Male
2  Priya  Female  priya@gmail.com    7000  Priya Female

In [126]:
df

    name  gender            email  salary   name_gender  salary1
0  Ankit    Male  ankit@gmail.com    5000    Ankit Male     5000
1  Rahul    Male  rahul@gmail.com    6000    Rahul Male     6000
2  Priya  Female  priya@gmail.com    7000  Priya Female     7000

In [128]:
df.sort_values(by = 'name', inplace=True)

In [130]:
df.sort_values(by = 'salary', ascending=False)

    name  gender            email  salary   name_gender  salary1
2  Priya  Female  priya@gmail.com    7000  Priya Female     7000
1  Rahul    Male  rahul@gmail.com    6000    Rahul Male     6000
0  Ankit    Male  ankit@gmail.com    5000    Ankit Male     5000

In [133]:
df.sort_values(by = ['gender','salary'], ascending=[False,True])

    name  gender            email  salary   name_gender  salary1
0  Ankit    Male  ankit@gmail.com    5000    Ankit Male     5000
1  Rahul    Male  rahul@gmail.com    6000    Rahul Male     6000
2  Priya  Female  priya@gmail.com    7000  Priya Female     7000

In [135]:
df.sort_values(by = ['gender','salary'], ascending=False, inplace=True)

In [141]:
df.sort_index(ascending=False)