In [1]:
emp={'name':'Sudhanshu','Gender':'Male','email':'sudhanshur4746@gmail.com'}
emp

{'name': 'Sudhanshu', 'Gender': 'Male', 'email': 'sudhanshur4746@gmail.com'}

In [2]:
emp= {"name":["Ankit","Rahul","Priya"],"gender":["Male","Male","Female"], "email":["ankit@gmail.com","rahul@gmail.com","priya@gmail.com"] }
emp

{'name': ['Ankit', 'Rahul', 'Priya'],
 'gender': ['Male', 'Male', 'Female'],
 'email': ['ankit@gmail.com', 'rahul@gmail.com', 'priya@gmail.com']}

In [3]:
import pandas as pd

In [5]:
df_emp=pd.DataFrame(emp)
df_emp

    name  gender            email
0  Ankit    Male  ankit@gmail.com
1  Rahul    Male  rahul@gmail.com
2  Priya  Female  priya@gmail.com

In [6]:
df_emp['name']

0    Ankit
1    Rahul
2    Priya
Name: name, dtype: object

In [8]:
#another method to accessing the element 
df_emp.name

0    Ankit
1    Rahul
2    Priya
Name: name, dtype: object

In [9]:
df_emp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      object
 1   gender  3 non-null      object
 2   email   3 non-null      object
dtypes: object(3)
memory usage: 204.0+ bytes

In [10]:
df_emp.describe()

         name gender            email
count       3      3                3
unique      3      2                3
top     Ankit   Male  ankit@gmail.com
freq        1      2                1

In [11]:
#iloc & loc for acessing the element row wise / iloc only use in indexing or integer value 
df_emp.iloc[0]

name                Ankit
gender               Male
email     ankit@gmail.com
Name: 0, dtype: object

In [13]:
df_emp

    name  gender            email
0  Ankit    Male  ankit@gmail.com
1  Rahul    Male  rahul@gmail.com
2  Priya  Female  priya@gmail.com

In [15]:
df_emp.iloc[[0,2],0]

0    Ankit
2    Priya
Name: name, dtype: object

In [16]:
#specific rows/columns
df_emp.iloc[[0,2],[0,2]]

    name            email
0  Ankit  ankit@gmail.com
2  Priya  priya@gmail.com

In [19]:
#loc is labled based
df_emp

    name  gender            email
0  Ankit    Male  ankit@gmail.com
1  Rahul    Male  rahul@gmail.com
2  Priya  Female  priya@gmail.com

In [20]:
df_emp.loc[0,'name']

'Ankit'

In [22]:
df_emp.loc[0,['name','email']]

name               Ankit
email    ankit@gmail.com
Name: 0, dtype: object

In [23]:
df_emp.loc[0:2,['name','email']]

    name            email
0  Ankit  ankit@gmail.com
1  Rahul  rahul@gmail.com
2  Priya  priya@gmail.com

In [25]:
df_emp.loc[0:2,'name':'email']

    name  gender            email
0  Ankit    Male  ankit@gmail.com
1  Rahul    Male  rahul@gmail.com
2  Priya  Female  priya@gmail.com

In [26]:
df_emp.set_index('email')

                  name  gender
email
ankit@gmail.com  Ankit    Male
rahul@gmail.com  Rahul    Male
priya@gmail.com  Priya  Female

In [29]:
df_emp

    name  gender            email
0  Ankit    Male  ankit@gmail.com
1  Rahul    Male  rahul@gmail.com
2  Priya  Female  priya@gmail.com

In [41]:
#if we want to change the our data frame according to inder then use inplace 
df_emp.set_index('email',inplace=True)

In [42]:
df_emp

                  name  gender
email
ankit@gmail.com  Ankit    Male
rahul@gmail.com  Rahul    Male
priya@gmail.com  Priya  Female

In [44]:
df_emp.sort_index()
df_emp.sort_index(ascending=False)

                  name  gender
email
rahul@gmail.com  Rahul    Male
priya@gmail.com  Priya  Female
ankit@gmail.com  Ankit    Male

In [32]:
df_emp.loc[['ankit@gmail.com','priya@gmail.com'],'name':'gender']

                  name  gender
email
ankit@gmail.com  Ankit    Male
priya@gmail.com  Priya  Female

In [34]:
df_emp.reset_index(inplace=True)

In [35]:
df_emp

             email   name  gender
0  ankit@gmail.com  Ankit    Male
1  rahul@gmail.com  Rahul    Male
2  priya@gmail.com  Priya  Female

In [45]:
fc=(df_emp['gender']=='Male')

In [46]:
df_emp[fc]

                  name gender
email
ankit@gmail.com  Ankit   Male
rahul@gmail.com  Rahul   Male

In [47]:
df_emp[(df_emp['gender']=='Male')]

                  name gender
email
ankit@gmail.com  Ankit   Male
rahul@gmail.com  Rahul   Male

In [48]:
fci = ~(df_emp['gender']=='Male')

In [49]:
fci

email
ankit@gmail.com    False
rahul@gmail.com    False
priya@gmail.com     True
Name: gender, dtype: bool

In [50]:
df_emp[fci]

                  name  gender
email
priya@gmail.com  Priya  Female

NameError: name 'df' is not defined