In [1]:
import pandas as pd

In [2]:
emp= {"name":["Ankit","Rahul","Priya"],"gender":["Male","Male","Female"], "email":["ankit@gmail.com","rahul@gmail.com","priya@gmail.com"] }
df1 = pd.DataFrame(emp)
df1

    name  gender            email
0  Ankit    Male  ankit@gmail.com
1  Rahul    Male  rahul@gmail.com
2  Priya  Female  priya@gmail.com

In [4]:
emp= {"name":["Sudhanshu","vishal","Priyanshu"],"gender":["Male","Male","Female"], "email":["sudhanshu@gmail.com","vishal@gmail.com","priyanshu@gmail.com"] }
df2 = pd.DataFrame(emp)
df2

        name  gender                email
0  Sudhanshu    Male  sudhanshu@gmail.com
1     vishal    Male     vishal@gmail.com
2  Priyanshu  Female  priyanshu@gmail.com

In [5]:
pd.concat([df1,df2])

        name  gender                email
0      Ankit    Male      ankit@gmail.com
1      Rahul    Male      rahul@gmail.com
2      Priya  Female      priya@gmail.com
0  Sudhanshu    Male  sudhanshu@gmail.com
1     vishal    Male     vishal@gmail.com
2  Priyanshu  Female  priyanshu@gmail.com

In [9]:
pd.concat([df1,df2],ignore_index=True)
#also use reset function
pd.concat([df1,df2]).reset_index()

   index       name  gender                email
0      0      Ankit    Male      ankit@gmail.com
1      1      Rahul    Male      rahul@gmail.com
2      2      Priya  Female      priya@gmail.com
3      0  Sudhanshu    Male  sudhanshu@gmail.com
4      1     vishal    Male     vishal@gmail.com
5      2  Priyanshu  Female  priyanshu@gmail.com

In [12]:

pd.concat([df1,df2], ignore_index=True,axis=1)

       0       1                2          3       4                    5
0  Ankit    Male  ankit@gmail.com  Sudhanshu    Male  sudhanshu@gmail.com
1  Rahul    Male  rahul@gmail.com     vishal    Male     vishal@gmail.com
2  Priya  Female  priya@gmail.com  Priyanshu  Female  priyanshu@gmail.com

In [16]:
emp= {"name":["Ankit","Rahul","Priya","Ankit"],"gender":["Male","Male","Female","Male"], "email":["ankit@gmail.com","rahul@gmail.com","priya@gmail.com","ankit@gmail.com"] }
df = pd.DataFrame(emp)
df

    name  gender            email
0  Ankit    Male  ankit@gmail.com
1  Rahul    Male  rahul@gmail.com
2  Priya  Female  priya@gmail.com
3  Ankit    Male  ankit@gmail.com

In [17]:
df.drop_duplicates()

    name  gender            email
0  Ankit    Male  ankit@gmail.com
1  Rahul    Male  rahul@gmail.com
2  Priya  Female  priya@gmail.com

In [18]:
emp= {"name":["Ankit","Rahul","Priya","vishal"],"gender":["Male","Male","Female","Male"], "email":["ankit@gmail.com","rahul@gmail.com","priya@gmail.com","ankit@gmail.com"] }
df = pd.DataFrame(emp)
df

     name  gender            email
0   Ankit    Male  ankit@gmail.com
1   Rahul    Male  rahul@gmail.com
2   Priya  Female  priya@gmail.com
3  vishal    Male  ankit@gmail.com

In [19]:
df.drop_duplicates()

     name  gender            email
0   Ankit    Male  ankit@gmail.com
1   Rahul    Male  rahul@gmail.com
2   Priya  Female  priya@gmail.com
3  vishal    Male  ankit@gmail.com

In [20]:
df.drop_duplicates(subset='email')

    name  gender            email
0  Ankit    Male  ankit@gmail.com
1  Rahul    Male  rahul@gmail.com
2  Priya  Female  priya@gmail.com

In [21]:
df.drop_duplicates(subset='email',keep='first')

    name  gender            email
0  Ankit    Male  ankit@gmail.com
1  Rahul    Male  rahul@gmail.com
2  Priya  Female  priya@gmail.com

In [22]:
df.drop_duplicates(subset='email',keep='last')

     name  gender            email
1   Rahul    Male  rahul@gmail.com
2   Priya  Female  priya@gmail.com
3  vishal    Male  ankit@gmail.com

In [25]:
df.drop_duplicates(subset=['email','gender'],keep='last')
#df.drop_duplicates(subset=['email','gender'],keep='last',inplace=true)

     name  gender            email
1   Rahul    Male  rahul@gmail.com
2   Priya  Female  priya@gmail.com
3  vishal    Male  ankit@gmail.com

In [26]:
df.drop_duplicates(subset=['email','gender'],keep=False)

    name  gender            email
1  Rahul    Male  rahul@gmail.com
2  Priya  Female  priya@gmail.com

In [28]:
dfg=df.groupby('email')['name'].count()
dfg[dfg.values>1]

email
ankit@gmail.com    2
Name: name, dtype: int64

In [44]:
import numpy as np
emp= {"name":["Ankit","Rahul","Priya",34],"gender":[np.nan,"Male","Female",np.nan], "email":["ankit@gmail.com","rahul@gmail.com",np.nan,np.nan] }
df = pd.DataFrame(emp)
df

    name  gender            email
0  Ankit     NaN  ankit@gmail.com
1  Rahul    Male  rahul@gmail.com
2  Priya  Female              NaN
3     34     NaN              NaN

In [37]:
df.isna()

    name  gender  email
0  False    True  False
1  False   False  False
2  False   False   True
3   True    True   True

In [38]:
df[df['gender'].isna()]

    name gender            email
0  Ankit    NaN  ankit@gmail.com
3    NaN    NaN              NaN

In [39]:
df.dropna()

    name gender            email
1  Rahul   Male  rahul@gmail.com

In [40]:
df.dropna(how='any')

    name gender            email
1  Rahul   Male  rahul@gmail.com

In [43]:
#df
df.dropna(how='all')

    name  gender            email
0  Ankit     NaN  ankit@gmail.com
1  Rahul    Male  rahul@gmail.com
2  Priya  Female              NaN

In [45]:
df.dropna(how='all',axis='columns')

    name  gender            email
0  Ankit     NaN  ankit@gmail.com
1  Rahul    Male  rahul@gmail.com
2  Priya  Female              NaN
3     34     NaN              NaN

In [46]:
df.dropna(how='any',axis='columns')

    name
0  Ankit
1  Rahul
2  Priya
3     34

In [47]:
df.dropna(subset=['name','email'],how='any',axis='index')

    name gender            email
0  Ankit    NaN  ankit@gmail.com
1  Rahul   Male  rahul@gmail.com

In [48]:
df['gender'].fillna(value='new_male',inplace=True)

C:\Users\sudha\AppData\Local\Temp\ipykernel_11688\3792563441.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['gender'].fillna(value='new_male',inplace=True)

In [49]:
df

    name    gender            email
0  Ankit  new_male  ankit@gmail.com
1  Rahul      Male  rahul@gmail.com
2  Priya    Female              NaN
3     34  new_male              NaN