In [1]:
import pandas as pd
emp= {"name":["Ankit","Rahul","Priya"],"gender":["Male","Male","Female"], "email":["ankit@gmail.com","rahul@gmail.com","priya@gmail.com"] }
emp

{'name': ['Ankit', 'Rahul', 'Priya'],
 'gender': ['Male', 'Male', 'Female'],
 'email': ['ankit@gmail.com', 'rahul@gmail.com', 'priya@gmail.com']}

In [52]:
df = pd.DataFrame(emp)
df

    name  gender            email
0  Ankit    Male  ankit@gmail.com
1  Rahul    Male  rahul@gmail.com
2  Priya  Female  priya@gmail.com

In [7]:
fc = (df['name']=='Ankit')
df[fc]
df.loc[0]

name                Ankit
gender               Male
email     ankit@gmail.com
Name: 0, dtype: object

In [12]:
#acessing the element using filter condition
print(df.loc[fc])
print(df.loc[fc,'gender'])

    name gender            email
0  Ankit   Male  ankit@gmail.com
0    Male
Name: gender, dtype: object

In [13]:
df.index =['a','b','c']
df

    name  gender            email
a  Ankit    Male  ankit@gmail.com
b  Rahul    Male  rahul@gmail.com
c  Priya  Female  priya@gmail.com

In [14]:
df.index =[0,1,2]
df

    name  gender            email
0  Ankit    Male  ankit@gmail.com
1  Rahul    Male  rahul@gmail.com
2  Priya  Female  priya@gmail.com

In [15]:
df.columns

Index(['name', 'gender', 'email'], dtype='object')

In [16]:
df.columns = ('emp_name','gender','emp_email')

In [17]:
df

  emp_name  gender        emp_email
0    Ankit    Male  ankit@gmail.com
1    Rahul    Male  rahul@gmail.com
2    Priya  Female  priya@gmail.com

In [19]:
df.rename(columns={'emp_name':'name','emp_email':'email'})

    name  gender            email
0  Ankit    Male  ankit@gmail.com
1  Rahul    Male  rahul@gmail.com
2  Priya  Female  priya@gmail.com

In [24]:
df.loc[0]=['Ankitt','Male','hapiness@gmail.com']

In [25]:
df

     name  gender               email
0  Ankitt    Male  hapiness@gmail.com
1   Rahul    Male     rahul@gmail.com
2   Priya  Female     priya@gmail.com

In [26]:
df.loc[0,'name']='Ankit'

In [27]:
df

    name  gender               email
0  Ankit    Male  hapiness@gmail.com
1  Rahul    Male     rahul@gmail.com
2  Priya  Female     priya@gmail.com

In [28]:
df.loc[0,['name','email']]=['Ankit','ankit@gmail.com']

In [29]:
df

    name  gender            email
0  Ankit    Male  ankit@gmail.com
1  Rahul    Male  rahul@gmail.com
2  Priya  Female  priya@gmail.com

In [30]:
fc=(df['gender']=='Male')

In [31]:
fc

0     True
1     True
2    False
Name: gender, dtype: bool

In [32]:
df.loc[fc]

    name gender            email
0  Ankit   Male  ankit@gmail.com
1  Rahul   Male  rahul@gmail.com

In [34]:
fc=(df['gender']=='Male')
df.loc[fc,'gender']='Female'

In [35]:
df

    name  gender            email
0  Ankit  Female  ankit@gmail.com
1  Rahul  Female  rahul@gmail.com
2  Priya  Female  priya@gmail.com

In [36]:
df['gender'].apply(len)

0    6
1    6
2    6
Name: gender, dtype: int64

In [37]:
def update_email(email):
    return email.upper()

In [38]:
df['email'].apply(update_email)

0    ANKIT@GMAIL.COM
1    RAHUL@GMAIL.COM
2    PRIYA@GMAIL.COM
Name: email, dtype: object

In [39]:
df.applymap(len)

C:\Users\sudha\AppData\Local\Temp\ipykernel_14320\1485728669.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(len)

   name  gender  email
0     5       6     15
1     5       6     15
2     5       6     15

In [40]:
df.applymap(update_email)

C:\Users\sudha\AppData\Local\Temp\ipykernel_14320\2509261660.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(update_email)

    name  gender            email
0  ANKIT  FEMALE  ANKIT@GMAIL.COM
1  RAHUL  FEMALE  RAHUL@GMAIL.COM
2  PRIYA  FEMALE  PRIYA@GMAIL.COM

In [41]:
df['name'].str.upper()

0    ANKIT
1    RAHUL
2    PRIYA
Name: name, dtype: object

In [42]:
df['name'].str.lower()

0    ankit
1    rahul
2    priya
Name: name, dtype: object

In [46]:
df['name'].str.contains('A')

0     True
1    False
2    False
Name: name, dtype: bool

In [48]:
df['name'].str.startswith('A')

0     True
1    False
2    False
Name: name, dtype: bool

In [76]:
#creating a new column
df['salary']=10000
df

    name  gender            email   name_gender  salary  salary1
0  Ankit    Male  ankit@gmail.com    Ankit Male   10000    60000
1  Rahul    Male  rahul@gmail.com    Rahul Male   10000    70000
2  Priya  Female  priya@gmail.com  Priya Female   10000    80000

In [77]:
df['name_gender']=df['name']+' '+df['gender']

In [78]:
df

    name  gender            email   name_gender  salary  salary1
0  Ankit    Male  ankit@gmail.com    Ankit Male   10000    60000
1  Rahul    Male  rahul@gmail.com    Rahul Male   10000    70000
2  Priya  Female  priya@gmail.com  Priya Female   10000    80000

In [79]:
df.loc[0,'salary']=20000
df

    name  gender            email   name_gender  salary  salary1
0  Ankit    Male  ankit@gmail.com    Ankit Male   20000    60000
1  Rahul    Male  rahul@gmail.com    Rahul Male   10000    70000
2  Priya  Female  priya@gmail.com  Priya Female   10000    80000

In [80]:
df.loc[(df['name']=='Ankit'),'salary']=30000
df

    name  gender            email   name_gender  salary  salary1
0  Ankit    Male  ankit@gmail.com    Ankit Male   30000    60000
1  Rahul    Male  rahul@gmail.com    Rahul Male   10000    70000
2  Priya  Female  priya@gmail.com  Priya Female   10000    80000

In [81]:
df['salary1']=[60000,70000,80000]
df

    name  gender            email   name_gender  salary  salary1
0  Ankit    Male  ankit@gmail.com    Ankit Male   30000    60000
1  Rahul    Male  rahul@gmail.com    Rahul Male   10000    70000
2  Priya  Female  priya@gmail.com  Priya Female   10000    80000

In [82]:
#delete rows 
df.drop(index =0)
#for change in the original data frame we have to use the inplace=True
#df.drop(index=0,inplace=True

    name  gender            email   name_gender  salary  salary1
1  Rahul    Male  rahul@gmail.com    Rahul Male   10000    70000
2  Priya  Female  priya@gmail.com  Priya Female   10000    80000

In [86]:
print(df)
fc = (df['salary1']>60000)
fc

    name  gender            email   name_gender  salary  salary1
0  Ankit    Male  ankit@gmail.com    Ankit Male   30000    60000
1  Rahul    Male  rahul@gmail.com    Rahul Male   10000    70000
2  Priya  Female  priya@gmail.com  Priya Female   10000    80000

0    False
1     True
2     True
Name: salary1, dtype: bool

In [87]:
#delete column 
df.drop(columns='salary1')

    name  gender            email   name_gender  salary
0  Ankit    Male  ankit@gmail.com    Ankit Male   30000
1  Rahul    Male  rahul@gmail.com    Rahul Male   10000
2  Priya  Female  priya@gmail.com  Priya Female   10000

In [90]:
df.sort_values(by='name',inplace=True)

In [91]:
df

    name  gender            email   name_gender  salary  salary1
0  Ankit    Male  ankit@gmail.com    Ankit Male   30000    60000
2  Priya  Female  priya@gmail.com  Priya Female   10000    80000
1  Rahul    Male  rahul@gmail.com    Rahul Male   10000    70000

In [93]:
df.sort_values(by='salary1',ascending =False)

    name  gender            email   name_gender  salary  salary1
2  Priya  Female  priya@gmail.com  Priya Female   10000    80000
1  Rahul    Male  rahul@gmail.com    Rahul Male   10000    70000
0  Ankit    Male  ankit@gmail.com    Ankit Male   30000    60000

In [95]:
df.sort_values(by=['gender','salary1'],ascending =False,inplace=True)

In [96]:
df

    name  gender            email   name_gender  salary  salary1
1  Rahul    Male  rahul@gmail.com    Rahul Male   10000    70000
0  Ankit    Male  ankit@gmail.com    Ankit Male   30000    60000
2  Priya  Female  priya@gmail.com  Priya Female   10000    80000

In [97]:
df.sort_index(ascending =False)

    name  gender            email   name_gender  salary  salary1
2  Priya  Female  priya@gmail.com  Priya Female   10000    80000
1  Rahul    Male  rahul@gmail.com    Rahul Male   10000    70000
0  Ankit    Male  ankit@gmail.com    Ankit Male   30000    60000