In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('orders.txt')

In [3]:
df

,order_id,order_date,customer_name,city,category,product_id,sales,profit
0,CA-2018-100006,2018-09-07,Dennis Kane,New York City,Technology,TEC-PH-10002075,377.970,109.6113
1,CA-2018-100090,2018-07-08,Ed Braxton,San Francisco,Furniture,FUR-TA-10003715,502.488,-87.9354
2,CA-2018-100293,2018-03-14,Neil Französisch,Jacksonville,Office Supplies,OFF-PA-10000176,91.056,31.8696
3,CA-2018-100328,2018-01-28,Jasper Cacioppo,New York City,Office Supplies,OFF-BI-10000343,3.928,1.3257
4,CA-2018-100363,2018-04-08,Jim Mitchum,Glendale,Office Supplies,OFF-FA-10000611,2.368,0.8288
...,...,...,...,...,...,...,...,...
5004,US-2021-168802,2021-11-03,Jack O'Briant,Seattle,Office Supplies,OFF-BI-10002393,18.368,5.9696
5005,US-2021-169320,2021-07-23,Lena Hernandez,Elkhart,Office Supplies,OFF-AR-10003602,11.680,5.4896
5006,US-2021-169488,2021-09-07,Allen Armold,Providence,Office Supplies,OFF-PA-10000157,39.960,18.7812
5007,US-2021-169502,2021-08-28,Matthew Grinstein,Milwaukee,Office Supplies,OFF-AP-10001947,91.600,26.5640
5008,US-2021-169551,2021-07-07,Rob Lucas,Philadelphia,Furniture,FUR-BO-10001519,87.210,-45.3492

In [4]:
df.head()

,order_id,order_date,customer_name,city,category,product_id,sales,profit
0,CA-2018-100006,2018-09-07,Dennis Kane,New York City,Technology,TEC-PH-10002075,377.970,109.6113
1,CA-2018-100090,2018-07-08,Ed Braxton,San Francisco,Furniture,FUR-TA-10003715,502.488,-87.9354
2,CA-2018-100293,2018-03-14,Neil Französisch,Jacksonville,Office Supplies,OFF-PA-10000176,91.056,31.8696
3,CA-2018-100328,2018-01-28,Jasper Cacioppo,New York City,Office Supplies,OFF-BI-10000343,3.928,1.3257
4,CA-2018-100363,2018-04-08,Jim Mitchum,Glendale,Office Supplies,OFF-FA-10000611,2.368,0.8288

In [8]:
print(df['sales'].sum())
print(df['sales'].mean())
print(df['sales'].max())

1107592.9048
221.12056394489917
10499.97

In [9]:
fc = (df['category']=='Furniture')
fc

0       False
1        True
2       False
3       False
4       False
        ...
5004    False
5005    False
5006    False
5007    False
5008     True
Name: category, Length: 5009, dtype: bool

In [10]:
df[fc]['sales'].sum()

np.float64(628359.3048)

In [11]:
df.groupby('category')['sales'].sum()

category
Furniture          628359.3048
Office Supplies    298596.7520
Technology         180636.8480
Name: sales, dtype: float64

In [12]:
df_cat_sales=df.groupby('category')['sales'].sum()

In [14]:
df_cat_sales.index

Index(['Furniture', 'Office Supplies', 'Technology'], dtype='object', name='category')

In [15]:
df_cat_sales.values

array([628359.3048, 298596.752 , 180636.848 ])

In [16]:
type(df_cat_sales)

pandas.core.series.Series

In [19]:
#convert into dataFrame
pd.DataFrame({'category': df_cat_sales.index,'sales':df_cat_sales.values})

          category        sales
0        Furniture  628359.3048
1  Office Supplies  298596.7520
2       Technology  180636.8480

In [20]:
dfc = df.groupby(['category','city'])['sales'].sum()

In [21]:
dfc

category    city
Furniture   Akron          433.5960
            Alexandria     204.6400
            Allen          244.0060
            Allentown       11.6480
            Amarillo      3048.5828
                            ...
Technology  Wichita        224.7500
            Wilmington     694.3560
            Woodland       239.9840
            Yonkers        216.4000
            Yuma           785.5130
Name: sales, Length: 987, dtype: float64

In [22]:
dfc.index

MultiIndex([( 'Furniture',           'Akron'),
            ( 'Furniture',      'Alexandria'),
            ( 'Furniture',           'Allen'),
            ( 'Furniture',       'Allentown'),
            ( 'Furniture',        'Amarillo'),
            ( 'Furniture',         'Anaheim'),
            ( 'Furniture',         'Andover'),
            ( 'Furniture',          'Apopka'),
            ( 'Furniture',    'Apple Valley'),
            ( 'Furniture',       'Arlington'),
            ...
            ('Technology',         'Visalia'),
            ('Technology',         'Warwick'),
            ('Technology', 'West Palm Beach'),
            ('Technology',     'Westminster'),
            ('Technology',        'Whittier'),
            ('Technology',         'Wichita'),
            ('Technology',      'Wilmington'),
            ('Technology',        'Woodland'),
            ('Technology',         'Yonkers'),
            ('Technology',            'Yuma')],
           names=['category', 'city'], length=987)

In [25]:
dfc = df.groupby(['category','city'], as_index=False)['sales'].sum()

In [26]:
dfc

       category        city      sales
0     Furniture       Akron   433.5960
1     Furniture  Alexandria   204.6400
2     Furniture       Allen   244.0060
3     Furniture   Allentown    11.6480
4     Furniture    Amarillo  3048.5828
..          ...         ...        ...
982  Technology     Wichita   224.7500
983  Technology  Wilmington   694.3560
984  Technology    Woodland   239.9840
985  Technology     Yonkers   216.4000
986  Technology        Yuma   785.5130

[987 rows x 3 columns]

In [27]:
dfc = df.groupby('category').agg({'sales':'sum','profit':'sum'})

In [28]:
dfc

                       sales      profit
category
Furniture        628359.3048  17310.8435
Office Supplies  298596.7520  52426.7106
Technology       180636.8480  35613.7076

In [29]:
dfc = df.groupby('category', as_index=False).agg({'sales':'sum','profit':'sum'})

In [30]:
dfc

          category        sales      profit
0        Furniture  628359.3048  17310.8435
1  Office Supplies  298596.7520  52426.7106
2       Technology  180636.8480  35613.7076

In [31]:
dfc = df.groupby('category', as_index=False).agg({'sales':'sum','profit':'min'})

In [32]:
dfc

          category        sales     profit
0        Furniture  628359.3048 -1862.3124
1  Office Supplies  298596.7520 -2929.4845
2       Technology  180636.8480  -571.9956

In [33]:
#merge ot join 
dfr= pd.read_csv('returns.txt')

In [34]:
dfr

           Order Id Return Reason
0    CA-2020-104689   Wrong Items
1    CA-2020-105081   Wrong Items
2    CA-2020-105291   Wrong Items
3    CA-2020-105585   Wrong Items
4    CA-2020-106950   Wrong Items
..              ...           ...
291  US-2021-136679        Others
292  US-2021-147886        Others
293  US-2021-147998   Wrong Items
294  US-2021-151127   Wrong Items
295  US-2021-155999   Wrong Items

[296 rows x 2 columns]

In [38]:
dfr.rename(columns = {'Order Id':'order_id', 'Return Reason':'Return_reason'},inplace=True)
dfr

           order_id Return_reason
0    CA-2020-104689   Wrong Items
1    CA-2020-105081   Wrong Items
2    CA-2020-105291   Wrong Items
3    CA-2020-105585   Wrong Items
4    CA-2020-106950   Wrong Items
..              ...           ...
291  US-2021-136679        Others
292  US-2021-147886        Others
293  US-2021-147998   Wrong Items
294  US-2021-151127   Wrong Items
295  US-2021-155999   Wrong Items

[296 rows x 2 columns]

In [41]:
pd.merge(left=df, right=dfr, how = 'inner',left_on='order_id',right_on = 'order_id')

,order_id,order_date,customer_name,city,category,product_id,sales,profit,Return_reason
0,CA-2018-100762,2018-11-24,Nat Gilpin,Jackson,Office Supplies,OFF-AR-10000380,151.920,45.5760,Bad Quality
1,CA-2018-100867,2018-10-19,Eugene Hildebrand,Lakewood,Technology,TEC-PH-10004922,321.552,20.0970,Bad Quality
2,CA-2018-102652,2018-04-06,Andy Yotov,Los Angeles,Furniture,FUR-FU-10000747,91.960,15.6332,Bad Quality
3,CA-2018-103373,2018-05-18,Bruce Stewart,Cleveland,Technology,TEC-PH-10002885,779.796,-168.9558,Bad Quality
4,CA-2018-103744,2018-02-23,Michael Grace,El Paso,Office Supplies,OFF-BI-10000320,4.428,-6.8634,Bad Quality
...,...,...,...,...,...,...,...,...,...
291,US-2021-136679,2021-11-14,Xylona Preis,Pasadena,Office Supplies,OFF-AR-10003582,45.040,4.5040,Others
292,US-2021-147886,2021-03-28,Dave Hallsten,Fairfield,Furniture,FUR-FU-10001095,26.480,10.0624,Others
293,US-2021-147998,2021-05-19,Sue Ann Reed,San Jose,Office Supplies,OFF-BI-10002082,133.120,49.9200,Wrong Items
294,US-2021-151127,2021-05-22,Rob Lucas,Los Angeles,Office Supplies,OFF-AR-10002445,49.560,18.8328,Wrong Items
295,US-2021-155999,2021-08-07,Jay Kimmel,San Diego,Office Supplies,OFF-BI-10000404,13.760,4.6440,Wrong Items

In [42]:
pd.merge(left=df, right=dfr,how='inner', left_on='order_id',right_on = 'order_id')

,order_id,order_date,customer_name,city,category,product_id,sales,profit,Return_reason
0,CA-2018-100762,2018-11-24,Nat Gilpin,Jackson,Office Supplies,OFF-AR-10000380,151.920,45.5760,Bad Quality
1,CA-2018-100867,2018-10-19,Eugene Hildebrand,Lakewood,Technology,TEC-PH-10004922,321.552,20.0970,Bad Quality
2,CA-2018-102652,2018-04-06,Andy Yotov,Los Angeles,Furniture,FUR-FU-10000747,91.960,15.6332,Bad Quality
3,CA-2018-103373,2018-05-18,Bruce Stewart,Cleveland,Technology,TEC-PH-10002885,779.796,-168.9558,Bad Quality
4,CA-2018-103744,2018-02-23,Michael Grace,El Paso,Office Supplies,OFF-BI-10000320,4.428,-6.8634,Bad Quality
...,...,...,...,...,...,...,...,...,...
291,US-2021-136679,2021-11-14,Xylona Preis,Pasadena,Office Supplies,OFF-AR-10003582,45.040,4.5040,Others
292,US-2021-147886,2021-03-28,Dave Hallsten,Fairfield,Furniture,FUR-FU-10001095,26.480,10.0624,Others
293,US-2021-147998,2021-05-19,Sue Ann Reed,San Jose,Office Supplies,OFF-BI-10002082,133.120,49.9200,Wrong Items
294,US-2021-151127,2021-05-22,Rob Lucas,Los Angeles,Office Supplies,OFF-AR-10002445,49.560,18.8328,Wrong Items
295,US-2021-155999,2021-08-07,Jay Kimmel,San Diego,Office Supplies,OFF-BI-10000404,13.760,4.6440,Wrong Items

In [43]:
pd.merge(left=df, right=dfr,how='left', left_on='order_id',right_on = 'order_id')

,order_id,order_date,customer_name,city,category,product_id,sales,profit,Return_reason
0,CA-2018-100006,2018-09-07,Dennis Kane,New York City,Technology,TEC-PH-10002075,377.970,109.6113,NaN
1,CA-2018-100090,2018-07-08,Ed Braxton,San Francisco,Furniture,FUR-TA-10003715,502.488,-87.9354,NaN
2,CA-2018-100293,2018-03-14,Neil Französisch,Jacksonville,Office Supplies,OFF-PA-10000176,91.056,31.8696,NaN
3,CA-2018-100328,2018-01-28,Jasper Cacioppo,New York City,Office Supplies,OFF-BI-10000343,3.928,1.3257,NaN
4,CA-2018-100363,2018-04-08,Jim Mitchum,Glendale,Office Supplies,OFF-FA-10000611,2.368,0.8288,NaN
...,...,...,...,...,...,...,...,...,...
5004,US-2021-168802,2021-11-03,Jack O'Briant,Seattle,Office Supplies,OFF-BI-10002393,18.368,5.9696,NaN
5005,US-2021-169320,2021-07-23,Lena Hernandez,Elkhart,Office Supplies,OFF-AR-10003602,11.680,5.4896,NaN
5006,US-2021-169488,2021-09-07,Allen Armold,Providence,Office Supplies,OFF-PA-10000157,39.960,18.7812,NaN
5007,US-2021-169502,2021-08-28,Matthew Grinstein,Milwaukee,Office Supplies,OFF-AP-10001947,91.600,26.5640,NaN
5008,US-2021-169551,2021-07-07,Rob Lucas,Philadelphia,Furniture,FUR-BO-10001519,87.210,-45.3492,NaN

In [44]:
pd.merge(left=df, right=dfr,how='right', left_on='order_id',right_on = 'order_id')

,order_id,order_date,customer_name,city,category,product_id,sales,profit,Return_reason
0,CA-2020-104689,2020-12-01,Fred Hopkins,Los Angeles,Office Supplies,OFF-AR-10001149,23.040,6.9120,Wrong Items
1,CA-2020-105081,2020-12-25,Joe Elijah,Seattle,Furniture,FUR-CH-10000847,698.352,52.3764,Wrong Items
2,CA-2020-105291,2020-10-30,Susan Pistek,San Luis Obispo,Office Supplies,OFF-FA-10003059,3.620,1.1946,Wrong Items
3,CA-2020-105585,2020-08-26,Roland Fjeld,San Jose,Office Supplies,OFF-FA-10002983,10.230,4.9104,Wrong Items
4,CA-2020-106950,2020-09-02,Joe Elijah,Charlotte,Furniture,FUR-TA-10001768,472.518,-149.6307,Wrong Items
...,...,...,...,...,...,...,...,...,...
291,US-2021-136679,2021-11-14,Xylona Preis,Pasadena,Office Supplies,OFF-AR-10003582,45.040,4.5040,Others
292,US-2021-147886,2021-03-28,Dave Hallsten,Fairfield,Furniture,FUR-FU-10001095,26.480,10.0624,Others
293,US-2021-147998,2021-05-19,Sue Ann Reed,San Jose,Office Supplies,OFF-BI-10002082,133.120,49.9200,Wrong Items
294,US-2021-151127,2021-05-22,Rob Lucas,Los Angeles,Office Supplies,OFF-AR-10002445,49.560,18.8328,Wrong Items
295,US-2021-155999,2021-08-07,Jay Kimmel,San Diego,Office Supplies,OFF-BI-10000404,13.760,4.6440,Wrong Items

In [45]:
pd.merge(left=df, right=dfr,how='outer', left_on='order_id',right_on = 'order_id')

,order_id,order_date,customer_name,city,category,product_id,sales,profit,Return_reason
0,CA-2018-100006,2018-09-07,Dennis Kane,New York City,Technology,TEC-PH-10002075,377.970,109.6113,NaN
1,CA-2018-100090,2018-07-08,Ed Braxton,San Francisco,Furniture,FUR-TA-10003715,502.488,-87.9354,NaN
2,CA-2018-100293,2018-03-14,Neil Französisch,Jacksonville,Office Supplies,OFF-PA-10000176,91.056,31.8696,NaN
3,CA-2018-100328,2018-01-28,Jasper Cacioppo,New York City,Office Supplies,OFF-BI-10000343,3.928,1.3257,NaN
4,CA-2018-100363,2018-04-08,Jim Mitchum,Glendale,Office Supplies,OFF-FA-10000611,2.368,0.8288,NaN
...,...,...,...,...,...,...,...,...,...
5004,US-2021-168802,2021-11-03,Jack O'Briant,Seattle,Office Supplies,OFF-BI-10002393,18.368,5.9696,NaN
5005,US-2021-169320,2021-07-23,Lena Hernandez,Elkhart,Office Supplies,OFF-AR-10003602,11.680,5.4896,NaN
5006,US-2021-169488,2021-09-07,Allen Armold,Providence,Office Supplies,OFF-PA-10000157,39.960,18.7812,NaN
5007,US-2021-169502,2021-08-28,Matthew Grinstein,Milwaukee,Office Supplies,OFF-AP-10001947,91.600,26.5640,NaN
5008,US-2021-169551,2021-07-07,Rob Lucas,Philadelphia,Furniture,FUR-BO-10001519,87.210,-45.3492,NaN

In [47]:
pd.merge(left=df, right=dfr,how='cross')

,order_id_x,order_date,customer_name,city,category,product_id,sales,profit,order_id_y,Return_reason
0,CA-2018-100006,2018-09-07,Dennis Kane,New York City,Technology,TEC-PH-10002075,377.97,109.6113,CA-2020-104689,Wrong Items
1,CA-2018-100006,2018-09-07,Dennis Kane,New York City,Technology,TEC-PH-10002075,377.97,109.6113,CA-2020-105081,Wrong Items
2,CA-2018-100006,2018-09-07,Dennis Kane,New York City,Technology,TEC-PH-10002075,377.97,109.6113,CA-2020-105291,Wrong Items
3,CA-2018-100006,2018-09-07,Dennis Kane,New York City,Technology,TEC-PH-10002075,377.97,109.6113,CA-2020-105585,Wrong Items
4,CA-2018-100006,2018-09-07,Dennis Kane,New York City,Technology,TEC-PH-10002075,377.97,109.6113,CA-2020-106950,Wrong Items
...,...,...,...,...,...,...,...,...,...,...
1482659,US-2021-169551,2021-07-07,Rob Lucas,Philadelphia,Furniture,FUR-BO-10001519,87.21,-45.3492,US-2021-136679,Others
1482660,US-2021-169551,2021-07-07,Rob Lucas,Philadelphia,Furniture,FUR-BO-10001519,87.21,-45.3492,US-2021-147886,Others
1482661,US-2021-169551,2021-07-07,Rob Lucas,Philadelphia,Furniture,FUR-BO-10001519,87.21,-45.3492,US-2021-147998,Wrong Items
1482662,US-2021-169551,2021-07-07,Rob Lucas,Philadelphia,Furniture,FUR-BO-10001519,87.21,-45.3492,US-2021-151127,Wrong Items
1482663,US-2021-169551,2021-07-07,Rob Lucas,Philadelphia,Furniture,FUR-BO-10001519,87.21,-45.3492,US-2021-155999,Wrong Items