In [ ]:
import pandas as pd

In [5]:
df= pd.read_csv('orders.txt')
type(df)

pandas.core.frame.DataFrame

In [3]:
df

,order_id,order_date,customer_name,city,category,product_id,sales,profit
0,CA-2018-100006,2018-09-07,Dennis Kane,New York City,Technology,TEC-PH-10002075,377.970,109.6113
1,CA-2018-100090,2018-07-08,Ed Braxton,San Francisco,Furniture,FUR-TA-10003715,502.488,-87.9354
2,CA-2018-100293,2018-03-14,Neil Französisch,Jacksonville,Office Supplies,OFF-PA-10000176,91.056,31.8696
3,CA-2018-100328,2018-01-28,Jasper Cacioppo,New York City,Office Supplies,OFF-BI-10000343,3.928,1.3257
4,CA-2018-100363,2018-04-08,Jim Mitchum,Glendale,Office Supplies,OFF-FA-10000611,2.368,0.8288
...,...,...,...,...,...,...,...,...
5004,US-2021-168802,2021-11-03,Jack O'Briant,Seattle,Office Supplies,OFF-BI-10002393,18.368,5.9696
5005,US-2021-169320,2021-07-23,Lena Hernandez,Elkhart,Office Supplies,OFF-AR-10003602,11.680,5.4896
5006,US-2021-169488,2021-09-07,Allen Armold,Providence,Office Supplies,OFF-PA-10000157,39.960,18.7812
5007,US-2021-169502,2021-08-28,Matthew Grinstein,Milwaukee,Office Supplies,OFF-AP-10001947,91.600,26.5640
5008,US-2021-169551,2021-07-07,Rob Lucas,Philadelphia,Furniture,FUR-BO-10001519,87.210,-45.3492

In [7]:
print(df.head(10))
print(df.tail(10))

         order_id  order_date     customer_name           city  \
0  CA-2018-100006  2018-09-07       Dennis Kane  New York City
1  CA-2018-100090  2018-07-08        Ed Braxton  San Francisco
2  CA-2018-100293  2018-03-14  Neil Französisch   Jacksonville
3  CA-2018-100328  2018-01-28   Jasper Cacioppo  New York City
4  CA-2018-100363  2018-04-08       Jim Mitchum       Glendale
5  CA-2018-100391  2018-05-25     Barry Weirich  New York City
6  CA-2018-100678  2018-04-18      Kunst Miller        Houston
7  CA-2018-100706  2018-12-16   Laurel Elliston    Springfield
8  CA-2018-100762  2018-11-24        Nat Gilpin        Jackson
9  CA-2018-100860  2018-03-26     Cindy Stewart         Pomona

          category       product_id    sales    profit
0       Technology  TEC-PH-10002075  377.970  109.6113
1        Furniture  FUR-TA-10003715  502.488  -87.9354
2  Office Supplies  OFF-PA-10000176   91.056   31.8696
3  Office Supplies  OFF-BI-10000343    3.928    1.3257
4  Office Supplies  OFF-FA-10000611    2.368    0.8288
5  Office Supplies  OFF-PA-10001471   14.620    6.7252
6        Furniture  FUR-CH-10002602  317.058  -18.1176
7        Furniture  FUR-FU-10002268   29.460    9.7218
8  Office Supplies  OFF-AR-10000380  151.920   45.5760
9  Office Supplies  OFF-LA-10001982   18.750    9.0000
            order_id  order_date      customer_name           city  \
4999  US-2021-167570  2021-12-08        Emily Grady   Philadelphia
5000  US-2021-167920  2021-12-09           John Lee       Richmond
5001  US-2021-168116  2021-11-04     Grant Thornton     Burlington
5002  US-2021-168613  2021-10-08        Gary McGarr  New York City
5003  US-2021-168690  2021-01-07      Thais Sissman   Ormond Beach
5004  US-2021-168802  2021-11-03      Jack O'Briant        Seattle
5005  US-2021-169320  2021-07-23     Lena Hernandez        Elkhart
5006  US-2021-169488  2021-09-07       Allen Armold     Providence
5007  US-2021-169502  2021-08-28  Matthew Grinstein      Milwaukee
5008  US-2021-169551  2021-07-07          Rob Lucas   Philadelphia

             category       product_id    sales   profit
4999        Furniture  FUR-CH-10003396  215.544 -58.5048
5000  Office Supplies  OFF-AP-10000159  214.900  62.3210
5001  Office Supplies  OFF-AP-10002457  167.440  14.6510
5002        Furniture  FUR-CH-10002372  145.764   3.2392
5003  Office Supplies  OFF-BI-10000145    2.808  -1.9656
5004  Office Supplies  OFF-BI-10002393   18.368   5.9696
5005  Office Supplies  OFF-AR-10003602   11.680   5.4896
5006  Office Supplies  OFF-PA-10000157   39.960  18.7812
5007  Office Supplies  OFF-AP-10001947   91.600  26.5640
5008        Furniture  FUR-BO-10001519   87.210 -45.3492

In [8]:
df['order_id']

0       CA-2018-100006
1       CA-2018-100090
2       CA-2018-100293
3       CA-2018-100328
4       CA-2018-100363
             ...
5004    US-2021-168802
5005    US-2021-169320
5006    US-2021-169488
5007    US-2021-169502
5008    US-2021-169551
Name: order_id, Length: 5009, dtype: object

In [10]:
col=['order_id','order_date','category']
df[col]

            order_id  order_date         category
0     CA-2018-100006  2018-09-07       Technology
1     CA-2018-100090  2018-07-08        Furniture
2     CA-2018-100293  2018-03-14  Office Supplies
3     CA-2018-100328  2018-01-28  Office Supplies
4     CA-2018-100363  2018-04-08  Office Supplies
...              ...         ...              ...
5004  US-2021-168802  2021-11-03  Office Supplies
5005  US-2021-169320  2021-07-23  Office Supplies
5006  US-2021-169488  2021-09-07  Office Supplies
5007  US-2021-169502  2021-08-28  Office Supplies
5008  US-2021-169551  2021-07-07        Furniture

[5009 rows x 3 columns]

In [11]:
#another way of method to use multiple columns
df[['order_id','order_date','category']]

            order_id  order_date         category
0     CA-2018-100006  2018-09-07       Technology
1     CA-2018-100090  2018-07-08        Furniture
2     CA-2018-100293  2018-03-14  Office Supplies
3     CA-2018-100328  2018-01-28  Office Supplies
4     CA-2018-100363  2018-04-08  Office Supplies
...              ...         ...              ...
5004  US-2021-168802  2021-11-03  Office Supplies
5005  US-2021-169320  2021-07-23  Office Supplies
5006  US-2021-169488  2021-09-07  Office Supplies
5007  US-2021-169502  2021-08-28  Office Supplies
5008  US-2021-169551  2021-07-07        Furniture

[5009 rows x 3 columns]

In [13]:
df.iloc[[0,2,4],0]

0    CA-2018-100006
2    CA-2018-100293
4    CA-2018-100363
Name: order_id, dtype: object

In [14]:
df.iloc[2:6,1:3]

   order_date     customer_name
2  2018-03-14  Neil Französisch
3  2018-01-28   Jasper Cacioppo
4  2018-04-08       Jim Mitchum
5  2018-05-25     Barry Weirich

In [15]:
df.loc[2:6,['city','sales']]

            city    sales
2   Jacksonville   91.056
3  New York City    3.928
4       Glendale    2.368
5  New York City   14.620
6        Houston  317.058

In [16]:
#to get unique value of a column
df['category'].unique()

array(['Technology', 'Furniture', 'Office Supplies'], dtype=object)

In [19]:
df['category'].value_counts()

category
Office Supplies    2773
Furniture          1764
Technology          472
Name: count, dtype: int64

In [20]:
df['city'].value_counts()

city
New York City    450
Los Angeles      384
Philadelphia     265
San Francisco    265
Seattle          212
                ...
Burbank            1
Glenview           1
Jupiter            1
Ormond Beach       1
Elkhart            1
Name: count, Length: 531, dtype: int64

In [22]:
df[['category','city']].value_counts()

category         city
Office Supplies  New York City    257
                 Los Angeles      210
Furniture        New York City    157
Office Supplies  Philadelphia     152
                 San Francisco    149
                                 ...
Furniture        Boise              1
                 Bossier City       1
Technology       Thousand Oaks      1
                 Toledo             1
                 Spokane            1
Name: count, Length: 987, dtype: int64

In [23]:
fc = (df.category=='Furniture')

In [24]:
df[fc]

,order_id,order_date,customer_name,city,category,product_id,sales,profit
1,CA-2018-100090,2018-07-08,Ed Braxton,San Francisco,Furniture,FUR-TA-10003715,502.488,-87.9354
6,CA-2018-100678,2018-04-18,Kunst Miller,Houston,Furniture,FUR-CH-10002602,317.058,-18.1176
7,CA-2018-100706,2018-12-16,Laurel Elliston,Springfield,Furniture,FUR-FU-10002268,29.460,9.7218
13,CA-2018-100916,2018-10-21,Frank Hawley,Newport News,Furniture,FUR-TA-10004607,591.320,112.3508
21,CA-2018-101462,2018-04-20,Benjamin Patterson,Los Angeles,Furniture,FUR-FU-10000409,59.920,27.5632
...,...,...,...,...,...,...,...,...
4997,US-2021-167318,2021-07-26,George Zrebassa,Los Angeles,Furniture,FUR-CH-10000665,362.352,45.2940
4998,US-2021-167402,2021-01-13,Cathy Prescott,Springfield,Furniture,FUR-BO-10001608,212.940,53.2350
4999,US-2021-167570,2021-12-08,Emily Grady,Philadelphia,Furniture,FUR-CH-10003396,215.544,-58.5048
5002,US-2021-168613,2021-10-08,Gary McGarr,New York City,Furniture,FUR-CH-10002372,145.764,3.2392
5008,US-2021-169551,2021-07-07,Rob Lucas,Philadelphia,Furniture,FUR-BO-10001519,87.210,-45.3492

In [31]:
fc1 = (df.category=='Furniture')&(df.sales >= 2000)

In [32]:
df[fc1]

,order_id,order_date,customer_name,city,category,product_id,sales,profit
207,CA-2018-116246,2018-09-12,Luke Weiss,New York City,Furniture,FUR-CH-10002024,3785.2920,420.5880
245,CA-2018-120474,2018-12-01,Resi Pölking,Madison,Furniture,FUR-CH-10001854,2807.8400,673.8816
352,CA-2018-128209,2018-11-17,Greg Tran,Buffalo,Furniture,FUR-BO-10002213,4007.8400,-50.0980
395,CA-2018-131926,2018-06-01,Dianna Wilson,Lakeville,Furniture,FUR-CH-10004063,2001.8600,580.5394
776,CA-2018-167199,2018-01-06,Maria Etezadi,Henderson,Furniture,FUR-CH-10004063,2573.8200,746.4078
943,CA-2019-111038,2019-12-01,Lindsay Castell,San Diego,Furniture,FUR-CH-10003973,2676.6720,267.6672
1020,CA-2019-116638,2019-01-28,Joseph Holt,Concord,Furniture,FUR-TA-10000198,4297.6440,-1862.3124
1025,CA-2019-117086,2019-11-08,Quincy Jones,Burlington,Furniture,FUR-BO-10004834,4404.9000,1013.1270
1066,CA-2019-120677,2019-05-31,Bill Donatelli,Minneapolis,Furniture,FUR-CH-10002320,2567.8400,770.3520
1293,CA-2019-137113,2019-12-01,Tamara Willingham,Seattle,Furniture,FUR-CH-10001215,2003.9200,125.2450
1324,CA-2019-139731,2019-10-15,Joel Eaton,Amarillo,Furniture,FUR-CH-10002024,2453.4300,-350.4900
1591,CA-2019-160227,2019-11-02,Emily Ducich,New York City,Furniture,FUR-CH-10002073,2621.3220,553.3902
1637,CA-2019-164301,2019-03-26,Ellis Ballard,Seattle,Furniture,FUR-TA-10001889,3393.6800,610.8624
1645,CA-2019-164777,2019-01-27,Sean Christensen,Los Angeles,Furniture,FUR-CH-10002024,2803.9200,0.0000
1762,CA-2020-104157,2020-07-25,Meg Tillman,Jackson,Furniture,FUR-TA-10004915,2430.0800,388.8128
1806,CA-2020-107104,2020-11-26,Maribeth Schnelling,Los Angeles,Furniture,FUR-BO-10002213,3406.6640,160.3136
1833,CA-2020-108987,2020-09-08,Anna Gayman,Houston,Furniture,FUR-BO-10004834,2396.2656,-317.1528
1921,CA-2020-113831,2020-05-30,Anna Häberlin,Springfield,Furniture,FUR-TA-10002645,2275.5000,386.8350
2051,CA-2020-122903,2020-05-27,Laura Armstrong,Detroit,Furniture,FUR-CH-10002024,3504.9000,700.9800
2562,CA-2020-155530,2020-12-17,Charles McCrossin,San Francisco,Furniture,FUR-TA-10004256,2003.5200,-325.5720
2789,CA-2020-169670,2020-12-25,Joe Elijah,New York City,Furniture,FUR-CH-10002331,2563.0560,313.2624
2800,CA-2021-100111,2021-09-20,Seth Vernon,New York City,Furniture,FUR-CH-10001215,2254.4100,375.7350
2851,CA-2021-102204,2021-05-01,Caroline Jumper,Jacksonville,Furniture,FUR-CH-10002024,2803.9200,0.0000
3180,CA-2021-118892,2021-08-17,Tom Prescott,Philadelphia,Furniture,FUR-CH-10002024,4416.1740,-630.8820
3256,CA-2021-122490,2021-11-13,Ted Trevino,Seattle,Furniture,FUR-CH-10001215,2404.7040,150.2940
3290,CA-2021-123967,2021-11-01,Sarah Foster,Bellingham,Furniture,FUR-TA-10003954,2665.6200,239.9058
3796,CA-2021-149559,2021-09-11,Karen Ferguson,Long Beach,Furniture,FUR-CH-10002320,2054.2720,256.7840
3805,CA-2021-150091,2021-10-12,Nora Paige,Lakewood,Furniture,FUR-BO-10003404,2154.9000,129.2940
4408,US-2019-126977,2019-09-17,Peter Fuller,New York City,Furniture,FUR-BO-10002213,2003.9200,-25.0490
4458,US-2019-150630,2019-09-17,Tracy Blumstein,Philadelphia,Furniture,FUR-BO-10004834,3083.4300,-1665.0522
4580,US-2020-126452,2020-08-21,Scot Coram,Los Angeles,Furniture,FUR-TA-10003569,2887.0560,180.4410
4705,US-2020-164196,2020-11-11,Alejandro Savely,Noblesville,Furniture,FUR-TA-10001950,2678.9400,241.1046

In [30]:
fc = ~((df.category=='Furniture')&(df.sales >= 2000))
df[fc]

,order_id,order_date,customer_name,city,category,product_id,sales,profit
0,CA-2018-100006,2018-09-07,Dennis Kane,New York City,Technology,TEC-PH-10002075,377.970,109.6113
1,CA-2018-100090,2018-07-08,Ed Braxton,San Francisco,Furniture,FUR-TA-10003715,502.488,-87.9354
2,CA-2018-100293,2018-03-14,Neil Französisch,Jacksonville,Office Supplies,OFF-PA-10000176,91.056,31.8696
3,CA-2018-100328,2018-01-28,Jasper Cacioppo,New York City,Office Supplies,OFF-BI-10000343,3.928,1.3257
4,CA-2018-100363,2018-04-08,Jim Mitchum,Glendale,Office Supplies,OFF-FA-10000611,2.368,0.8288
...,...,...,...,...,...,...,...,...
5004,US-2021-168802,2021-11-03,Jack O'Briant,Seattle,Office Supplies,OFF-BI-10002393,18.368,5.9696
5005,US-2021-169320,2021-07-23,Lena Hernandez,Elkhart,Office Supplies,OFF-AR-10003602,11.680,5.4896
5006,US-2021-169488,2021-09-07,Allen Armold,Providence,Office Supplies,OFF-PA-10000157,39.960,18.7812
5007,US-2021-169502,2021-08-28,Matthew Grinstein,Milwaukee,Office Supplies,OFF-AP-10001947,91.600,26.5640
5008,US-2021-169551,2021-07-07,Rob Lucas,Philadelphia,Furniture,FUR-BO-10001519,87.210,-45.3492

In [33]:
df_fur=df[fc1]

In [36]:
df_fur

,order_id,order_date,customer_name,city,category,product_id,sales,profit
207,CA-2018-116246,2018-09-12,Luke Weiss,New York City,Furniture,FUR-CH-10002024,3785.2920,420.5880
245,CA-2018-120474,2018-12-01,Resi Pölking,Madison,Furniture,FUR-CH-10001854,2807.8400,673.8816
352,CA-2018-128209,2018-11-17,Greg Tran,Buffalo,Furniture,FUR-BO-10002213,4007.8400,-50.0980
395,CA-2018-131926,2018-06-01,Dianna Wilson,Lakeville,Furniture,FUR-CH-10004063,2001.8600,580.5394
776,CA-2018-167199,2018-01-06,Maria Etezadi,Henderson,Furniture,FUR-CH-10004063,2573.8200,746.4078
943,CA-2019-111038,2019-12-01,Lindsay Castell,San Diego,Furniture,FUR-CH-10003973,2676.6720,267.6672
1020,CA-2019-116638,2019-01-28,Joseph Holt,Concord,Furniture,FUR-TA-10000198,4297.6440,-1862.3124
1025,CA-2019-117086,2019-11-08,Quincy Jones,Burlington,Furniture,FUR-BO-10004834,4404.9000,1013.1270
1066,CA-2019-120677,2019-05-31,Bill Donatelli,Minneapolis,Furniture,FUR-CH-10002320,2567.8400,770.3520
1293,CA-2019-137113,2019-12-01,Tamara Willingham,Seattle,Furniture,FUR-CH-10001215,2003.9200,125.2450
1324,CA-2019-139731,2019-10-15,Joel Eaton,Amarillo,Furniture,FUR-CH-10002024,2453.4300,-350.4900
1591,CA-2019-160227,2019-11-02,Emily Ducich,New York City,Furniture,FUR-CH-10002073,2621.3220,553.3902
1637,CA-2019-164301,2019-03-26,Ellis Ballard,Seattle,Furniture,FUR-TA-10001889,3393.6800,610.8624
1645,CA-2019-164777,2019-01-27,Sean Christensen,Los Angeles,Furniture,FUR-CH-10002024,2803.9200,0.0000
1762,CA-2020-104157,2020-07-25,Meg Tillman,Jackson,Furniture,FUR-TA-10004915,2430.0800,388.8128
1806,CA-2020-107104,2020-11-26,Maribeth Schnelling,Los Angeles,Furniture,FUR-BO-10002213,3406.6640,160.3136
1833,CA-2020-108987,2020-09-08,Anna Gayman,Houston,Furniture,FUR-BO-10004834,2396.2656,-317.1528
1921,CA-2020-113831,2020-05-30,Anna Häberlin,Springfield,Furniture,FUR-TA-10002645,2275.5000,386.8350
2051,CA-2020-122903,2020-05-27,Laura Armstrong,Detroit,Furniture,FUR-CH-10002024,3504.9000,700.9800
2562,CA-2020-155530,2020-12-17,Charles McCrossin,San Francisco,Furniture,FUR-TA-10004256,2003.5200,-325.5720
2789,CA-2020-169670,2020-12-25,Joe Elijah,New York City,Furniture,FUR-CH-10002331,2563.0560,313.2624
2800,CA-2021-100111,2021-09-20,Seth Vernon,New York City,Furniture,FUR-CH-10001215,2254.4100,375.7350
2851,CA-2021-102204,2021-05-01,Caroline Jumper,Jacksonville,Furniture,FUR-CH-10002024,2803.9200,0.0000
3180,CA-2021-118892,2021-08-17,Tom Prescott,Philadelphia,Furniture,FUR-CH-10002024,4416.1740,-630.8820
3256,CA-2021-122490,2021-11-13,Ted Trevino,Seattle,Furniture,FUR-CH-10001215,2404.7040,150.2940
3290,CA-2021-123967,2021-11-01,Sarah Foster,Bellingham,Furniture,FUR-TA-10003954,2665.6200,239.9058
3796,CA-2021-149559,2021-09-11,Karen Ferguson,Long Beach,Furniture,FUR-CH-10002320,2054.2720,256.7840
3805,CA-2021-150091,2021-10-12,Nora Paige,Lakewood,Furniture,FUR-BO-10003404,2154.9000,129.2940
4408,US-2019-126977,2019-09-17,Peter Fuller,New York City,Furniture,FUR-BO-10002213,2003.9200,-25.0490
4458,US-2019-150630,2019-09-17,Tracy Blumstein,Philadelphia,Furniture,FUR-BO-10004834,3083.4300,-1665.0522
4580,US-2020-126452,2020-08-21,Scot Coram,Los Angeles,Furniture,FUR-TA-10003569,2887.0560,180.4410
4705,US-2020-164196,2020-11-11,Alejandro Savely,Noblesville,Furniture,FUR-TA-10001950,2678.9400,241.1046

In [37]:
df_fur.reset_index(inplace=True)

In [38]:
df_fur

,index,order_id,order_date,customer_name,city,category,product_id,sales,profit
0,207,CA-2018-116246,2018-09-12,Luke Weiss,New York City,Furniture,FUR-CH-10002024,3785.2920,420.5880
1,245,CA-2018-120474,2018-12-01,Resi Pölking,Madison,Furniture,FUR-CH-10001854,2807.8400,673.8816
2,352,CA-2018-128209,2018-11-17,Greg Tran,Buffalo,Furniture,FUR-BO-10002213,4007.8400,-50.0980
3,395,CA-2018-131926,2018-06-01,Dianna Wilson,Lakeville,Furniture,FUR-CH-10004063,2001.8600,580.5394
4,776,CA-2018-167199,2018-01-06,Maria Etezadi,Henderson,Furniture,FUR-CH-10004063,2573.8200,746.4078
5,943,CA-2019-111038,2019-12-01,Lindsay Castell,San Diego,Furniture,FUR-CH-10003973,2676.6720,267.6672
6,1020,CA-2019-116638,2019-01-28,Joseph Holt,Concord,Furniture,FUR-TA-10000198,4297.6440,-1862.3124
7,1025,CA-2019-117086,2019-11-08,Quincy Jones,Burlington,Furniture,FUR-BO-10004834,4404.9000,1013.1270
8,1066,CA-2019-120677,2019-05-31,Bill Donatelli,Minneapolis,Furniture,FUR-CH-10002320,2567.8400,770.3520
9,1293,CA-2019-137113,2019-12-01,Tamara Willingham,Seattle,Furniture,FUR-CH-10001215,2003.9200,125.2450
10,1324,CA-2019-139731,2019-10-15,Joel Eaton,Amarillo,Furniture,FUR-CH-10002024,2453.4300,-350.4900
11,1591,CA-2019-160227,2019-11-02,Emily Ducich,New York City,Furniture,FUR-CH-10002073,2621.3220,553.3902
12,1637,CA-2019-164301,2019-03-26,Ellis Ballard,Seattle,Furniture,FUR-TA-10001889,3393.6800,610.8624
13,1645,CA-2019-164777,2019-01-27,Sean Christensen,Los Angeles,Furniture,FUR-CH-10002024,2803.9200,0.0000
14,1762,CA-2020-104157,2020-07-25,Meg Tillman,Jackson,Furniture,FUR-TA-10004915,2430.0800,388.8128
15,1806,CA-2020-107104,2020-11-26,Maribeth Schnelling,Los Angeles,Furniture,FUR-BO-10002213,3406.6640,160.3136
16,1833,CA-2020-108987,2020-09-08,Anna Gayman,Houston,Furniture,FUR-BO-10004834,2396.2656,-317.1528
17,1921,CA-2020-113831,2020-05-30,Anna Häberlin,Springfield,Furniture,FUR-TA-10002645,2275.5000,386.8350
18,2051,CA-2020-122903,2020-05-27,Laura Armstrong,Detroit,Furniture,FUR-CH-10002024,3504.9000,700.9800
19,2562,CA-2020-155530,2020-12-17,Charles McCrossin,San Francisco,Furniture,FUR-TA-10004256,2003.5200,-325.5720
20,2789,CA-2020-169670,2020-12-25,Joe Elijah,New York City,Furniture,FUR-CH-10002331,2563.0560,313.2624
21,2800,CA-2021-100111,2021-09-20,Seth Vernon,New York City,Furniture,FUR-CH-10001215,2254.4100,375.7350
22,2851,CA-2021-102204,2021-05-01,Caroline Jumper,Jacksonville,Furniture,FUR-CH-10002024,2803.9200,0.0000
23,3180,CA-2021-118892,2021-08-17,Tom Prescott,Philadelphia,Furniture,FUR-CH-10002024,4416.1740,-630.8820
24,3256,CA-2021-122490,2021-11-13,Ted Trevino,Seattle,Furniture,FUR-CH-10001215,2404.7040,150.2940
25,3290,CA-2021-123967,2021-11-01,Sarah Foster,Bellingham,Furniture,FUR-TA-10003954,2665.6200,239.9058
26,3796,CA-2021-149559,2021-09-11,Karen Ferguson,Long Beach,Furniture,FUR-CH-10002320,2054.2720,256.7840
27,3805,CA-2021-150091,2021-10-12,Nora Paige,Lakewood,Furniture,FUR-BO-10003404,2154.9000,129.2940
28,4408,US-2019-126977,2019-09-17,Peter Fuller,New York City,Furniture,FUR-BO-10002213,2003.9200,-25.0490
29,4458,US-2019-150630,2019-09-17,Tracy Blumstein,Philadelphia,Furniture,FUR-BO-10004834,3083.4300,-1665.0522
30,4580,US-2020-126452,2020-08-21,Scot Coram,Los Angeles,Furniture,FUR-TA-10003569,2887.0560,180.4410
31,4705,US-2020-164196,2020-11-11,Alejandro Savely,Noblesville,Furniture,FUR-TA-10001950,2678.9400,241.1046

In [39]:
pd.set_option('display.max_rows',None)
pd.set_option('display.max_columns',None)

In [40]:
fc=(df.category=='Furniture') | (df.category == 'Technology')

In [43]:
df[fc]

,order_id,order_date,customer_name,city,category,product_id,sales,profit
0,CA-2018-100006,2018-09-07,Dennis Kane,New York City,Technology,TEC-PH-10002075,377.9700,109.6113
1,CA-2018-100090,2018-07-08,Ed Braxton,San Francisco,Furniture,FUR-TA-10003715,502.4880,-87.9354
6,CA-2018-100678,2018-04-18,Kunst Miller,Houston,Furniture,FUR-CH-10002602,317.0580,-18.1176
7,CA-2018-100706,2018-12-16,Laurel Elliston,Springfield,Furniture,FUR-FU-10002268,29.4600,9.7218
10,CA-2018-100867,2018-10-19,Eugene Hildebrand,Lakewood,Technology,TEC-PH-10004922,321.5520,20.0970
11,CA-2018-100881,2018-03-28,Daniel Raglin,Albuquerque,Technology,TEC-PH-10003273,302.3760,22.6782
13,CA-2018-100916,2018-10-21,Frank Hawley,Newport News,Furniture,FUR-TA-10004607,591.3200,112.3508
21,CA-2018-101462,2018-04-20,Benjamin Patterson,Los Angeles,Furniture,FUR-FU-10000409,59.9200,27.5632
22,CA-2018-101476,2018-09-12,Shirley Daniels,New Rochelle,Technology,TEC-MA-10000029,69.9900,30.0957
23,CA-2018-101560,2018-11-28,Chris Selesnick,Columbia,Furniture,FUR-FU-10003773,397.6000,43.7360
24,CA-2018-101602,2018-12-15,Mick Crebagga,El Paso,Furniture,FUR-CH-10004675,763.2800,-21.8080
27,CA-2018-101931,2018-10-28,Todd Sumrall,Los Angeles,Furniture,FUR-BO-10001337,616.9980,-36.2940
31,CA-2018-102295,2018-11-24,Erica Hackney,Sacramento,Furniture,FUR-CH-10001714,120.7120,-18.1068
34,CA-2018-102652,2018-04-06,Andy Yotov,Los Angeles,Furniture,FUR-FU-10000747,91.9600,15.6332
36,CA-2018-102869,2018-09-09,Logan Currie,Philadelphia,Furniture,FUR-FU-10002456,17.4720,5.0232
38,CA-2018-103058,2018-07-23,Alejandro Grove,New York City,Technology,TEC-AC-10001314,99.9800,7.9984
39,CA-2018-103086,2018-10-17,Evan Bailliet,Houston,Furniture,FUR-FU-10004586,5.3120,-1.5936
42,CA-2018-103219,2018-11-09,Benjamin Farhat,New York City,Furniture,FUR-FU-10004091,56.5200,21.4776
43,CA-2018-103310,2018-05-10,Greg Matthias,San Jose,Furniture,FUR-CH-10002320,256.7840,32.0980
44,CA-2018-103317,2018-07-05,Don Miller,Palm Coast,Furniture,FUR-FU-10001591,19.5200,5.3680
45,CA-2018-103331,2018-08-26,Karl Braun,Newark,Furniture,FUR-FU-10001731,10.6800,4.0584
46,CA-2018-103366,2018-01-15,Erica Hackney,Roswell,Technology,TEC-AC-10003628,149.9500,65.9780
47,CA-2018-103373,2018-05-18,Bruce Stewart,Cleveland,Technology,TEC-PH-10002885,779.7960,-168.9558
53,CA-2018-103660,2018-08-25,Mitch Webber,Seattle,Technology,TEC-PH-10000895,1007.9440,75.5958
58,CA-2018-103849,2018-05-11,Paul Gonzalez,Fort Worth,Furniture,FUR-FU-10000723,66.1120,-84.2928
59,CA-2018-103940,2018-09-17,Bradley Nguyen,Seattle,Furniture,FUR-FU-10004671,35.3400,13.4292
60,CA-2018-103989,2018-03-19,Matt Connell,Lakeland,Furniture,FUR-FU-10002508,20.0160,5.5044
61,CA-2018-104178,2018-08-25,Janet Molinari,Los Angeles,Furniture,FUR-FU-10000771,6.2800,2.6376
62,CA-2018-104269,2018-03-01,Dave Brooks,Seattle,Furniture,FUR-CH-10004063,457.5680,51.4764
63,CA-2018-104283,2018-06-27,Liz MacKendrick,Southaven,Furniture,FUR-TA-10001039,85.9800,22.3548
64,CA-2018-104402,2018-06-17,Duane Benoit,Newark,Technology,TEC-MA-10000423,65.9700,31.0059
65,CA-2018-104472,2018-06-02,Christine Kargatis,Orem,Furniture,FUR-FU-10000246,73.3200,21.9960
66,CA-2018-104563,2018-03-07,Craig Molinari,Seattle,Furniture,FUR-CH-10002780,436.7040,21.8352
73,CA-2018-105165,2018-09-07,Sam Zeldin,Houston,Furniture,FUR-TA-10004154,200.7950,-22.9480
75,CA-2018-105249,2018-11-28,Duane Huffman,San Francisco,Furniture,FUR-BO-10000330,411.3320,-4.8392
76,CA-2018-105270,2018-11-11,Arthur Prichep,Los Angeles,Furniture,FUR-CH-10000988,112.6480,11.2648
78,CA-2018-105417,2018-01-07,Vivek Sundaresam,Huntsville,Furniture,FUR-FU-10004864,76.7280,-53.7096
79,CA-2018-105648,2018-03-03,Eva Jacobs,San Diego,Furniture,FUR-TA-10002958,626.3520,-23.4882
82,CA-2018-105984,2018-11-24,Muhammed Yedwab,Columbus,Furniture,FUR-CH-10000847,611.0580,-34.9176
84,CA-2018-106229,2018-06-07,Nick Radford,Aurora,Furniture,FUR-TA-10002041,268.9350,-209.7693
85,CA-2018-106264,2018-12-26,Clytie Kelty,San Diego,Furniture,FUR-FU-10001852,3.4800,1.1136
87,CA-2018-106439,2018-10-31,Greg Guthrie,Los Angeles,Furniture,FUR-CH-10003833,146.3520,-9.1470
92,CA-2018-106810,2018-05-14,Anthony Johnson,Saint Petersburg,Furniture,FUR-FU-10004306,310.8800,23.3160
93,CA-2018-106971,2018-09-02,Bryan Mills,Buffalo Grove,Technology,TEC-AC-10000844,475.9440,95.1888
98,CA-2018-107454,2018-11-02,Roger Demir,New York City,Furniture,FUR-FU-10004018,89.3400,24.1218
103,CA-2018-107755,2018-02-07,Cyma Kinney,Linden,Technology,TEC-AC-10000710,115.3600,49.6048
104,CA-2018-107769,2018-10-28,Bill Tyler,Garden City,Technology,TEC-PH-10001336,257.9800,74.8142
105,CA-2018-107811,2018-04-29,Laura Armstrong,Memphis,Furniture,FUR-CH-10001394,561.5840,70.1980
106,CA-2018-107818,2018-09-08,Marc Crier,Pasco,Furniture,FUR-CH-10000454,975.9200,121.9900
107,CA-2018-107916,2018-08-24,Jennifer Patt,Oceanside,Furniture,FUR-FU-10004586,13.2800,6.3744
111,CA-2018-108273,2018-12-16,Ed Jacobs,Huntsville,Furniture,FUR-FU-10002116,56.5680,-74.9526
112,CA-2018-108609,2018-10-31,Anthony Jacobs,Lorain,Furniture,FUR-TA-10003954,1421.6640,-734.5264
118,CA-2018-109134,2018-11-05,Deanra Eno,Los Angeles,Furniture,FUR-FU-10000320,20.0400,8.8176
120,CA-2018-109232,2018-01-13,Natalie DeCherney,Mount Pleasant,Furniture,FUR-CH-10000422,545.9400,87.3504
122,CA-2018-109491,2018-02-20,Linda Cazamias,Richmond,Furniture,FUR-FU-10000221,20.3200,6.9088
125,CA-2018-109890,2018-07-21,Patrick Gardner,Omaha,Technology,TEC-PH-10004100,35.9800,10.0744
126,CA-2018-109897,2018-08-12,Ben Wallace,San Francisco,Furniture,FUR-FU-10002878,85.4400,31.6128
130,CA-2018-110030,2018-12-06,Luke Foster,Houston,Furniture,FUR-FU-10002759,23.9760,-14.3856
132,CA-2018-110072,2018-10-22,Maureen Gastineau,Newark,Furniture,FUR-FU-10000521,93.8880,12.9096
133,CA-2018-110100,2018-04-25,Lena Creighton,Wilmington,Technology,TEC-PH-10004531,302.3760,37.7970
135,CA-2018-110219,2018-05-05,Emily Burns,San Antonio,Furniture,FUR-CH-10001146,127.8690,-9.1335
137,CA-2018-110408,2018-10-18,Alan Schoenberger,Montgomery,Furniture,FUR-CH-10003774,545.8800,70.9644
138,CA-2018-110422,2018-01-21,Tom Boeckenhauer,Miami,Furniture,FUR-FU-10001889,25.2480,4.1028
143,CA-2018-110786,2018-12-29,Anthony Johnson,San Francisco,Furniture,FUR-FU-10000550,24.9000,8.2170
149,CA-2018-111192,2018-07-30,Tom Stivers,Seattle,Furniture,FUR-BO-10002916,1367.8400,259.8896
151,CA-2018-111451,2018-12-26,Kelly Lampkin,Colorado Springs,Furniture,FUR-CH-10001891,230.3520,20.1558
155,CA-2018-111871,2018-03-18,Eileen Kiefer,San Francisco,Furniture,FUR-BO-10004218,1198.3300,70.4900
159,CA-2018-112158,2018-12-02,David Philippe,New York City,Furniture,FUR-BO-10003272,883.9200,-110.4900
164,CA-2018-112837,2018-09-11,Liz Willingham,Oxnard,Furniture,FUR-FU-10004006,127.9500,21.7515
168,CA-2018-113257,2018-12-16,Sean Christensen,Beaumont,Furniture,FUR-FU-10001706,8.6240,-2.5872
169,CA-2018-113271,2018-07-09,Darrin Sayre,San Francisco,Furniture,FUR-BO-10004218,119.8330,7.0490
170,CA-2018-113320,2018-12-12,Logan Haushalter,Oakland,Furniture,FUR-FU-10001706,9.2400,4.4352
172,CA-2018-113383,2018-09-10,Sandra Flanagan,Clifton,Furniture,FUR-FU-10001986,254.9000,76.4700
174,CA-2018-113768,2018-05-13,Aaron Hawkins,Los Angeles,Furniture,FUR-CH-10002439,279.4560,20.9592
175,CA-2018-113859,2018-09-13,Becky Castell,Odessa,Furniture,FUR-CH-10004698,340.1160,-9.7176
176,CA-2018-113880,2018-03-01,Vicky Freymann,Elmhurst,Furniture,FUR-CH-10000863,634.1160,-172.1172
181,CA-2018-114181,2018-05-10,Art Foster,Philadelphia,Furniture,FUR-BO-10004467,349.9650,-216.9783
182,CA-2018-114195,2018-11-01,Erin Ashbrook,Mason,Furniture,FUR-FU-10002253,68.7040,16.3172
183,CA-2018-114251,2018-11-05,Maribeth Dona,Philadelphia,Furniture,FUR-FU-10001468,273.5680,-34.1960
184,CA-2018-114314,2018-10-11,Dorothy Badders,Fayetteville,Furniture,FUR-FU-10002107,8.9200,3.9248
185,CA-2018-114321,2018-08-20,Nick Crebassa,Hampton,Furniture,FUR-CH-10001797,500.2400,145.0696
186,CA-2018-114335,2018-09-28,Xylona Preis,Hollywood,Furniture,FUR-FU-10000277,337.0880,16.8544
187,CA-2018-114433,2018-05-13,Naresj Patel,Oakland,Technology,TEC-AC-10002800,149.9700,52.4895
189,CA-2018-114517,2018-12-23,Tiffany House,New York City,Furniture,FUR-TA-10001676,53.3160,-19.5492
192,CA-2018-115049,2018-09-26,Michael Moore,Chicago,Technology,TEC-AC-10004859,153.8240,38.4560
194,CA-2018-115084,2018-10-18,Luke Schmidt,Texarkana,Furniture,FUR-CH-10004626,605.3400,145.2816
196,CA-2018-115161,2018-01-31,Liz Carlisle,Mission Viejo,Furniture,FUR-BO-10003966,290.6660,3.4196
199,CA-2018-115357,2018-08-06,Roland Fjeld,Columbia,Technology,TEC-AC-10000023,62.9100,22.6476
200,CA-2018-115791,2018-01-16,Delfina Latchford,Philadelphia,Furniture,FUR-FU-10001095,127.1040,28.5984
201,CA-2018-115812,2018-06-09,Brosina Hoffman,Los Angeles,Furniture,FUR-FU-10001487,48.8600,14.1694
205,CA-2018-116190,2018-07-26,Sheri Gordon,Atlanta,Furniture,FUR-CH-10000553,67.8800,18.3276
207,CA-2018-116246,2018-09-12,Luke Weiss,New York City,Furniture,FUR-CH-10002024,3785.2920,420.5880
209,CA-2018-116568,2018-12-14,Bryan Mills,Deltona,Furniture,FUR-CH-10002439,186.3040,13.9728
210,CA-2018-116666,2018-05-08,Kean Thornton,Philadelphia,Technology,TEC-CO-10001449,1799.9700,239.9960
211,CA-2018-116673,2018-12-15,Jas O'Carroll,San Diego,Furniture,FUR-FU-10003829,6.1600,1.9712
214,CA-2018-116834,2018-10-11,Dean percer,Seattle,Furniture,FUR-FU-10001196,63.4700,19.0410
216,CA-2018-116932,2018-07-21,Michelle Ellison,San Francisco,Furniture,FUR-CH-10001215,801.5680,50.0980
219,CA-2018-117345,2018-08-01,Barbara Fisher,Charlotte,Furniture,FUR-FU-10000629,44.1280,12.1352
220,CA-2018-117429,2018-10-07,Mathew Reese,Philadelphia,Furniture,FUR-FU-10000222,129.9200,21.1120
221,CA-2018-117464,2018-07-22,Naresj Patel,San Francisco,Furniture,FUR-CH-10000155,717.7200,71.7720
225,CA-2018-117765,2018-09-07,Rick Bensley,Tulsa,Furniture,FUR-CH-10004698,161.9600,45.3488
227,CA-2018-118276,2018-12-29,Michael Granlund,Saint Charles,Furniture,FUR-FU-10002111,8.7360,-4.8048
228,CA-2018-118304,2018-04-29,Katherine Hughes,Dover,Technology,TEC-PH-10000376,19.9800,5.1948
230,CA-2018-118962,2018-08-05,Chad Sievert,Los Angeles,Furniture,FUR-CH-10003817,340.1440,21.2590
233,CA-2018-119144,2018-11-16,Justin Deggeller,Los Angeles,Furniture,FUR-BO-10004015,305.9745,25.1979
234,CA-2018-119151,2018-11-25,Mike Pelletier,New York City,Furniture,FUR-BO-10003159,275.9520,-37.9434
236,CA-2018-119375,2018-11-17,Yoseph Carroll,Newark,Furniture,FUR-FU-10002379,124.4100,14.9292
237,CA-2018-119466,2018-12-15,Sung Pak,Chicago,Furniture,FUR-FU-10001546,8.5440,-7.4760
243,CA-2018-120411,2018-09-20,Sarah Brown,Chicago,Furniture,FUR-BO-10004218,493.4300,-70.4900
245,CA-2018-120474,2018-12-01,Resi Pölking,Madison,Furniture,FUR-CH-10001854,2807.8400,673.8816
246,CA-2018-120544,2018-11-23,Saphhira Shifley,Mesquite,Furniture,FUR-FU-10001940,6.3680,-2.5472
247,CA-2018-120670,2018-11-02,Julie Kriz,Fort Lauderdale,Technology,TEC-AC-10004171,799.9200,239.9760
248,CA-2018-120768,2018-12-19,Irene Maddox,Florence,Furniture,FUR-CH-10000513,1819.8600,163.7874
249,CA-2018-120775,2018-10-03,Russell D'Ascenzo,Dallas,Furniture,FUR-FU-10000758,31.7760,-19.0656
252,CA-2018-120887,2018-09-27,Thomas Seio,Hackensack,Furniture,FUR-FU-10001588,87.5400,37.6422
254,CA-2018-121006,2018-11-10,Sam Craven,Midland,Furniture,FUR-CH-10004997,563.9400,112.7880
258,CA-2018-121629,2018-11-28,Brian Thompson,Houston,Technology,TEC-MA-10004679,998.8500,-199.7700
262,CA-2018-121769,2018-04-08,John Stevenson,Toledo,Furniture,FUR-TA-10004442,172.1100,-94.6605
264,CA-2018-122217,2018-11-24,Harold Pawlan,Virginia Beach,Furniture,FUR-FU-10002045,111.1500,48.9060
267,CA-2018-122588,2018-11-25,Andy Reiter,Woonsocket,Furniture,FUR-FU-10001095,52.9600,20.1248
268,CA-2018-122609,2018-11-12,Darren Powers,Carrollton,Furniture,FUR-FU-10004587,25.1280,-6.9102
270,CA-2018-122749,2018-12-03,Nathan Gelder,Oklahoma City,Technology,TEC-PH-10003811,479.9600,134.3888
271,CA-2018-122882,2018-09-07,Sean Braxton,Philadelphia,Furniture,FUR-FU-10000758,42.3680,8.4736
272,CA-2018-122931,2018-09-29,Suzanne McNair,Philadelphia,Furniture,FUR-TA-10004147,67.1760,-20.1528
277,CA-2018-123260,2018-08-26,Frank Merwin,Los Angeles,Technology,TEC-AC-10002323,176.8000,22.9840
278,CA-2018-123295,2018-07-18,Adrian Hane,Tucson,Furniture,FUR-CH-10002372,259.1360,-25.9136
285,CA-2018-123855,2018-06-18,Mick Crebagga,Los Angeles,Technology,TEC-PH-10000215,139.8000,12.2325
287,CA-2018-124023,2018-04-07,Pauline Johnson,Mobile,Furniture,FUR-FU-10004415,8.9600,2.7776
288,CA-2018-124079,2018-12-13,Randy Ferguson,Phoenix,Furniture,FUR-FU-10002553,87.9600,7.6965
289,CA-2018-124247,2018-12-16,Stefanie Holloman,Sacramento,Furniture,FUR-CH-10001854,1403.9200,70.1960
291,CA-2018-124429,2018-05-27,Maya Herman,San Diego,Furniture,FUR-TA-10002607,567.1200,-28.3560
293,CA-2018-124478,2018-08-08,Matt Abelman,Trenton,Furniture,FUR-FU-10002088,53.8800,22.6296
295,CA-2018-124618,2018-05-02,Cari Schnelling,Lakeland,Technology,TEC-CO-10004202,479.9840,89.9970
297,CA-2018-124688,2018-08-27,Corey Catlett,Springfield,Furniture,FUR-FU-10002456,29.1200,12.5216
298,CA-2018-124702,2018-11-18,Maya Herman,Seattle,Furniture,FUR-FU-10003553,137.5400,55.0160
299,CA-2018-124709,2018-07-27,Giulietta Weimer,San Francisco,Technology,TEC-AC-10002842,238.0000,38.0800
300,CA-2018-124723,2018-08-05,Gary Zandusky,Texas City,Furniture,FUR-TA-10001307,489.2300,41.9340
302,CA-2018-124737,2018-08-23,Arthur Prichep,Denver,Furniture,FUR-FU-10003274,4.2240,1.2672
304,CA-2018-124856,2018-09-29,Lisa DeCherney,New York City,Furniture,FUR-FU-10000521,117.3600,36.3816
306,CA-2018-125150,2018-05-16,Pauline Webber,Los Angeles,Furniture,FUR-CH-10002439,232.8800,17.4660
313,CA-2018-125731,2018-09-10,Clay Ludtke,Gresham,Furniture,FUR-CH-10003973,1487.0400,148.7040
314,CA-2018-125759,2018-02-08,Nathan Mautz,North Las Vegas,Furniture,FUR-FU-10002111,14.5600,5.5328
315,CA-2018-125829,2018-11-04,William Brown,Los Angeles,Furniture,FUR-TA-10002041,573.7280,-64.5444
316,CA-2018-125997,2018-09-20,Mitch Webber,New York City,Furniture,FUR-BO-10002213,801.5680,-10.0196
317,CA-2018-126032,2018-06-23,Brian Stugart,Philadelphia,Technology,TEC-AC-10000158,86.3760,1.0797
323,CA-2018-126403,2018-09-09,Rick Reed,Lowell,Furniture,FUR-CH-10003761,785.8800,212.1876
326,CA-2018-126683,2018-09-29,Paul Prost,Seattle,Furniture,FUR-FU-10001706,6.1600,2.9568
327,CA-2018-126760,2018-07-26,Kunst Miller,North Las Vegas,Furniture,FUR-CH-10003312,674.3520,-109.5822
328,CA-2018-126802,2018-12-29,Zuschuss Carroll,Chicago,Furniture,FUR-FU-10000193,38.9760,-50.6688
331,CA-2018-127012,2018-08-11,Greg Matthias,Seattle,Furniture,FUR-FU-10003691,12.3500,5.4340
333,CA-2018-127159,2018-05-12,Hunter Lopez,Milwaukee,Furniture,FUR-FU-10000010,34.7900,10.7849
334,CA-2018-127166,2018-05-21,Katherine Hughes,Houston,Furniture,FUR-CH-10003396,107.7720,-29.2524
335,CA-2018-127187,2018-12-04,Cathy Prescott,New York City,Technology,TEC-PH-10000673,129.9800,62.3904
338,CA-2018-127446,2018-11-25,Matt Collister,Arlington,Furniture,FUR-FU-10000221,6.0960,-3.9624
341,CA-2018-127558,2018-11-15,Shahid Shariari,Los Angeles,Furniture,FUR-FU-10002505,10.1100,3.2352
343,CA-2018-127614,2018-02-11,Natalie Fritzler,Chesapeake,Furniture,FUR-TA-10003715,1256.2200,75.3732
352,CA-2018-128209,2018-11-17,Greg Tran,Buffalo,Furniture,FUR-BO-10002213,4007.8400,-50.0980
364,CA-2018-129189,2018-07-21,Harry Marie,Dallas,Furniture,FUR-CH-10004997,657.9300,-93.9900
368,CA-2018-129924,2018-07-12,Alyssa Crouse,San Francisco,Furniture,FUR-TA-10004575,698.3520,-17.4588
369,CA-2018-129938,2018-12-15,Ed Braxton,Philadelphia,Furniture,FUR-CH-10003774,445.8020,-108.2662
370,CA-2018-130092,2018-01-11,Seth Vernon,Dover,Furniture,FUR-FU-10000010,9.9400,3.0814
374,CA-2018-130428,2018-03-31,Trudy Glocke,Tampa,Furniture,FUR-CH-10002965,1125.4880,98.4802
375,CA-2018-130449,2018-09-06,Victoria Pisteka,San Francisco,Furniture,FUR-FU-10001487,41.8800,12.1452
378,CA-2018-130673,2018-05-20,Matt Collister,San Marcos,Furniture,FUR-FU-10003489,10.3320,-5.9409
384,CA-2018-131002,2018-09-07,Tom Boeckenhauer,Tulsa,Furniture,FUR-FU-10004270,57.6900,23.6529
385,CA-2018-131009,2018-03-01,Shahid Collister,El Paso,Furniture,FUR-CH-10001270,362.2500,0.0000
386,CA-2018-131051,2018-12-01,Toby Ritter,San Francisco,Furniture,FUR-FU-10001861,58.2000,28.5180
387,CA-2018-131247,2018-03-30,Guy Armstrong,San Francisco,Furniture,FUR-BO-10001337,205.6660,-12.0980
388,CA-2018-131310,2018-07-12,Clay Ludtke,Seattle,Furniture,FUR-CH-10001797,123.1360,13.8528
389,CA-2018-131387,2018-04-28,Arianne Irving,San Francisco,Technology,TEC-PH-10001459,1679.9600,125.9970
390,CA-2018-131450,2018-08-08,Lena Radford,San Diego,Furniture,FUR-FU-10001979,327.7600,91.7728
391,CA-2018-131527,2018-12-01,Toby Braunhardt,Jacksonville,Technology,TEC-PH-10001644,95.9680,9.5968
392,CA-2018-131541,2018-07-28,Chloris Kastensmidt,Apopka,Furniture,FUR-FU-10003623,129.8880,12.9888
395,CA-2018-131926,2018-06-01,Dianna Wilson,Lakeville,Furniture,FUR-CH-10004063,2001.8600,580.5394
399,CA-2018-132451,2018-09-26,Karen Ferguson,San Diego,Furniture,FUR-CH-10000454,585.5520,73.1940
400,CA-2018-132500,2018-09-08,Gary Zandusky,San Francisco,Technology,TEC-AC-10001383,49.9800,8.4966
402,CA-2018-132612,2018-06-09,Frank Olsen,Harrisonburg,Furniture,FUR-TA-10004534,1441.3000,245.0210
405,CA-2018-132864,2018-12-02,Katherine Nockton,Columbus,Technology,TEC-AC-10001267,119.8000,29.9500
408,CA-2018-132983,2018-04-28,David Smith,Jamestown,Technology,TEC-AC-10000736,159.9800,57.5928
409,CA-2018-133158,2018-08-19,David Wiener,Los Angeles,Furniture,FUR-FU-10000723,289.2400,26.0316
410,CA-2018-133228,2018-04-04,Maurice Satty,Detroit,Furniture,FUR-FU-10004020,5.4700,2.3521
417,CA-2018-133592,2018-12-31,Katherine Murray,Providence,Furniture,FUR-BO-10000362,341.9600,78.6508
418,CA-2018-133634,2018-11-05,Steven Roelle,Arlington,Technology,TEC-AC-10002550,47.7900,16.2486
419,CA-2018-133690,2018-08-03,Bruce Stewart,Denver,Furniture,FUR-TA-10004289,218.7500,-161.8750
426,CA-2018-134061,2018-04-29,Lauren Leatherbury,Rochester,Furniture,FUR-FU-10001424,17.4600,5.9364
429,CA-2018-134278,2018-07-06,Emily Phan,New York City,Technology,TEC-CO-10001046,559.9920,174.9975
431,CA-2018-134551,2018-12-20,Tony Sayre,Columbia,Furniture,FUR-CH-10004287,662.8800,74.5740
432,CA-2018-134572,2018-04-20,Seth Vernon,Houston,Furniture,FUR-TA-10001705,744.1000,-95.6700
434,CA-2018-134677,2018-10-06,Xylona Preis,San Diego,Technology,TEC-AC-10001445,9.0900,1.9089
435,CA-2018-134726,2018-11-02,Steven Ward,Seattle,Technology,TEC-AC-10000023,41.9400,15.0984
438,CA-2018-135608,2018-12-08,Jim Karlsson,Olympia,Furniture,FUR-CH-10002602,603.9200,45.2940
439,CA-2018-135657,2018-06-03,Steven Cartwright,Seattle,Furniture,FUR-TA-10004086,515.8800,113.4936
442,CA-2018-135993,2018-05-28,Patrick Jones,Seattle,Technology,TEC-AC-10004877,27.6000,2.2080
445,CA-2018-136399,2018-12-16,Chad Cunningham,Los Angeles,Furniture,FUR-CH-10002602,241.5680,18.1176
446,CA-2018-136567,2018-12-20,Penelope Sewall,Harrisonburg,Furniture,FUR-TA-10000617,455.1000,100.1220
447,CA-2018-136644,2018-06-16,Sonia Cooley,Mishawaka,Furniture,FUR-CH-10000225,647.8400,32.3920
449,CA-2018-136861,2018-09-05,Patrick Ryan,Saint Petersburg,Furniture,FUR-FU-10001967,31.9840,1.9990
451,CA-2018-137274,2018-03-29,Mike Gockenbach,Plano,Furniture,FUR-TA-10001889,890.8410,-152.7156
453,CA-2018-137575,2018-08-06,Trudy Brown,New York City,Technology,TEC-AC-10004571,199.9800,83.9916
457,CA-2018-138072,2018-12-30,Guy Armstrong,Philadelphia,Technology,TEC-AC-10004859,27.9680,6.9920
458,CA-2018-138100,2018-09-15,Alex Avila,New York City,Furniture,FUR-FU-10002456,14.5600,6.2608
460,CA-2018-138177,2018-09-19,Neil Ducich,Chandler,Furniture,FUR-TA-10004607,73.9150,-45.8273
464,CA-2018-138317,2018-06-21,Natalie Webber,Philadelphia,Furniture,FUR-FU-10000550,3.9840,0.6474
466,CA-2018-138436,2018-03-26,Jonathan Doherty,Los Angeles,Technology,TEC-AC-10002323,66.3000,8.6190

In [46]:
fc=(df.category=='Furniture') | (df.category == 'Technology')
cat=['Furniture','Technology']
fc1=df['category'].isin(cat)
df[fc1]

,order_id,order_date,customer_name,city,category,product_id,sales,profit
0,CA-2018-100006,2018-09-07,Dennis Kane,New York City,Technology,TEC-PH-10002075,377.9700,109.6113
1,CA-2018-100090,2018-07-08,Ed Braxton,San Francisco,Furniture,FUR-TA-10003715,502.4880,-87.9354
6,CA-2018-100678,2018-04-18,Kunst Miller,Houston,Furniture,FUR-CH-10002602,317.0580,-18.1176
7,CA-2018-100706,2018-12-16,Laurel Elliston,Springfield,Furniture,FUR-FU-10002268,29.4600,9.7218
10,CA-2018-100867,2018-10-19,Eugene Hildebrand,Lakewood,Technology,TEC-PH-10004922,321.5520,20.0970
11,CA-2018-100881,2018-03-28,Daniel Raglin,Albuquerque,Technology,TEC-PH-10003273,302.3760,22.6782
13,CA-2018-100916,2018-10-21,Frank Hawley,Newport News,Furniture,FUR-TA-10004607,591.3200,112.3508
21,CA-2018-101462,2018-04-20,Benjamin Patterson,Los Angeles,Furniture,FUR-FU-10000409,59.9200,27.5632
22,CA-2018-101476,2018-09-12,Shirley Daniels,New Rochelle,Technology,TEC-MA-10000029,69.9900,30.0957
23,CA-2018-101560,2018-11-28,Chris Selesnick,Columbia,Furniture,FUR-FU-10003773,397.6000,43.7360
24,CA-2018-101602,2018-12-15,Mick Crebagga,El Paso,Furniture,FUR-CH-10004675,763.2800,-21.8080
27,CA-2018-101931,2018-10-28,Todd Sumrall,Los Angeles,Furniture,FUR-BO-10001337,616.9980,-36.2940
31,CA-2018-102295,2018-11-24,Erica Hackney,Sacramento,Furniture,FUR-CH-10001714,120.7120,-18.1068
34,CA-2018-102652,2018-04-06,Andy Yotov,Los Angeles,Furniture,FUR-FU-10000747,91.9600,15.6332
36,CA-2018-102869,2018-09-09,Logan Currie,Philadelphia,Furniture,FUR-FU-10002456,17.4720,5.0232
38,CA-2018-103058,2018-07-23,Alejandro Grove,New York City,Technology,TEC-AC-10001314,99.9800,7.9984
39,CA-2018-103086,2018-10-17,Evan Bailliet,Houston,Furniture,FUR-FU-10004586,5.3120,-1.5936
42,CA-2018-103219,2018-11-09,Benjamin Farhat,New York City,Furniture,FUR-FU-10004091,56.5200,21.4776
43,CA-2018-103310,2018-05-10,Greg Matthias,San Jose,Furniture,FUR-CH-10002320,256.7840,32.0980
44,CA-2018-103317,2018-07-05,Don Miller,Palm Coast,Furniture,FUR-FU-10001591,19.5200,5.3680
45,CA-2018-103331,2018-08-26,Karl Braun,Newark,Furniture,FUR-FU-10001731,10.6800,4.0584
46,CA-2018-103366,2018-01-15,Erica Hackney,Roswell,Technology,TEC-AC-10003628,149.9500,65.9780
47,CA-2018-103373,2018-05-18,Bruce Stewart,Cleveland,Technology,TEC-PH-10002885,779.7960,-168.9558
53,CA-2018-103660,2018-08-25,Mitch Webber,Seattle,Technology,TEC-PH-10000895,1007.9440,75.5958
58,CA-2018-103849,2018-05-11,Paul Gonzalez,Fort Worth,Furniture,FUR-FU-10000723,66.1120,-84.2928
59,CA-2018-103940,2018-09-17,Bradley Nguyen,Seattle,Furniture,FUR-FU-10004671,35.3400,13.4292
60,CA-2018-103989,2018-03-19,Matt Connell,Lakeland,Furniture,FUR-FU-10002508,20.0160,5.5044
61,CA-2018-104178,2018-08-25,Janet Molinari,Los Angeles,Furniture,FUR-FU-10000771,6.2800,2.6376
62,CA-2018-104269,2018-03-01,Dave Brooks,Seattle,Furniture,FUR-CH-10004063,457.5680,51.4764
63,CA-2018-104283,2018-06-27,Liz MacKendrick,Southaven,Furniture,FUR-TA-10001039,85.9800,22.3548
64,CA-2018-104402,2018-06-17,Duane Benoit,Newark,Technology,TEC-MA-10000423,65.9700,31.0059
65,CA-2018-104472,2018-06-02,Christine Kargatis,Orem,Furniture,FUR-FU-10000246,73.3200,21.9960
66,CA-2018-104563,2018-03-07,Craig Molinari,Seattle,Furniture,FUR-CH-10002780,436.7040,21.8352
73,CA-2018-105165,2018-09-07,Sam Zeldin,Houston,Furniture,FUR-TA-10004154,200.7950,-22.9480
75,CA-2018-105249,2018-11-28,Duane Huffman,San Francisco,Furniture,FUR-BO-10000330,411.3320,-4.8392
76,CA-2018-105270,2018-11-11,Arthur Prichep,Los Angeles,Furniture,FUR-CH-10000988,112.6480,11.2648
78,CA-2018-105417,2018-01-07,Vivek Sundaresam,Huntsville,Furniture,FUR-FU-10004864,76.7280,-53.7096
79,CA-2018-105648,2018-03-03,Eva Jacobs,San Diego,Furniture,FUR-TA-10002958,626.3520,-23.4882
82,CA-2018-105984,2018-11-24,Muhammed Yedwab,Columbus,Furniture,FUR-CH-10000847,611.0580,-34.9176
84,CA-2018-106229,2018-06-07,Nick Radford,Aurora,Furniture,FUR-TA-10002041,268.9350,-209.7693
85,CA-2018-106264,2018-12-26,Clytie Kelty,San Diego,Furniture,FUR-FU-10001852,3.4800,1.1136
87,CA-2018-106439,2018-10-31,Greg Guthrie,Los Angeles,Furniture,FUR-CH-10003833,146.3520,-9.1470
92,CA-2018-106810,2018-05-14,Anthony Johnson,Saint Petersburg,Furniture,FUR-FU-10004306,310.8800,23.3160
93,CA-2018-106971,2018-09-02,Bryan Mills,Buffalo Grove,Technology,TEC-AC-10000844,475.9440,95.1888
98,CA-2018-107454,2018-11-02,Roger Demir,New York City,Furniture,FUR-FU-10004018,89.3400,24.1218
103,CA-2018-107755,2018-02-07,Cyma Kinney,Linden,Technology,TEC-AC-10000710,115.3600,49.6048
104,CA-2018-107769,2018-10-28,Bill Tyler,Garden City,Technology,TEC-PH-10001336,257.9800,74.8142
105,CA-2018-107811,2018-04-29,Laura Armstrong,Memphis,Furniture,FUR-CH-10001394,561.5840,70.1980
106,CA-2018-107818,2018-09-08,Marc Crier,Pasco,Furniture,FUR-CH-10000454,975.9200,121.9900
107,CA-2018-107916,2018-08-24,Jennifer Patt,Oceanside,Furniture,FUR-FU-10004586,13.2800,6.3744
111,CA-2018-108273,2018-12-16,Ed Jacobs,Huntsville,Furniture,FUR-FU-10002116,56.5680,-74.9526
112,CA-2018-108609,2018-10-31,Anthony Jacobs,Lorain,Furniture,FUR-TA-10003954,1421.6640,-734.5264
118,CA-2018-109134,2018-11-05,Deanra Eno,Los Angeles,Furniture,FUR-FU-10000320,20.0400,8.8176
120,CA-2018-109232,2018-01-13,Natalie DeCherney,Mount Pleasant,Furniture,FUR-CH-10000422,545.9400,87.3504
122,CA-2018-109491,2018-02-20,Linda Cazamias,Richmond,Furniture,FUR-FU-10000221,20.3200,6.9088
125,CA-2018-109890,2018-07-21,Patrick Gardner,Omaha,Technology,TEC-PH-10004100,35.9800,10.0744
126,CA-2018-109897,2018-08-12,Ben Wallace,San Francisco,Furniture,FUR-FU-10002878,85.4400,31.6128
130,CA-2018-110030,2018-12-06,Luke Foster,Houston,Furniture,FUR-FU-10002759,23.9760,-14.3856
132,CA-2018-110072,2018-10-22,Maureen Gastineau,Newark,Furniture,FUR-FU-10000521,93.8880,12.9096
133,CA-2018-110100,2018-04-25,Lena Creighton,Wilmington,Technology,TEC-PH-10004531,302.3760,37.7970
135,CA-2018-110219,2018-05-05,Emily Burns,San Antonio,Furniture,FUR-CH-10001146,127.8690,-9.1335
137,CA-2018-110408,2018-10-18,Alan Schoenberger,Montgomery,Furniture,FUR-CH-10003774,545.8800,70.9644
138,CA-2018-110422,2018-01-21,Tom Boeckenhauer,Miami,Furniture,FUR-FU-10001889,25.2480,4.1028
143,CA-2018-110786,2018-12-29,Anthony Johnson,San Francisco,Furniture,FUR-FU-10000550,24.9000,8.2170
149,CA-2018-111192,2018-07-30,Tom Stivers,Seattle,Furniture,FUR-BO-10002916,1367.8400,259.8896
151,CA-2018-111451,2018-12-26,Kelly Lampkin,Colorado Springs,Furniture,FUR-CH-10001891,230.3520,20.1558
155,CA-2018-111871,2018-03-18,Eileen Kiefer,San Francisco,Furniture,FUR-BO-10004218,1198.3300,70.4900
159,CA-2018-112158,2018-12-02,David Philippe,New York City,Furniture,FUR-BO-10003272,883.9200,-110.4900
164,CA-2018-112837,2018-09-11,Liz Willingham,Oxnard,Furniture,FUR-FU-10004006,127.9500,21.7515
168,CA-2018-113257,2018-12-16,Sean Christensen,Beaumont,Furniture,FUR-FU-10001706,8.6240,-2.5872
169,CA-2018-113271,2018-07-09,Darrin Sayre,San Francisco,Furniture,FUR-BO-10004218,119.8330,7.0490
170,CA-2018-113320,2018-12-12,Logan Haushalter,Oakland,Furniture,FUR-FU-10001706,9.2400,4.4352
172,CA-2018-113383,2018-09-10,Sandra Flanagan,Clifton,Furniture,FUR-FU-10001986,254.9000,76.4700
174,CA-2018-113768,2018-05-13,Aaron Hawkins,Los Angeles,Furniture,FUR-CH-10002439,279.4560,20.9592
175,CA-2018-113859,2018-09-13,Becky Castell,Odessa,Furniture,FUR-CH-10004698,340.1160,-9.7176
176,CA-2018-113880,2018-03-01,Vicky Freymann,Elmhurst,Furniture,FUR-CH-10000863,634.1160,-172.1172
181,CA-2018-114181,2018-05-10,Art Foster,Philadelphia,Furniture,FUR-BO-10004467,349.9650,-216.9783
182,CA-2018-114195,2018-11-01,Erin Ashbrook,Mason,Furniture,FUR-FU-10002253,68.7040,16.3172
183,CA-2018-114251,2018-11-05,Maribeth Dona,Philadelphia,Furniture,FUR-FU-10001468,273.5680,-34.1960
184,CA-2018-114314,2018-10-11,Dorothy Badders,Fayetteville,Furniture,FUR-FU-10002107,8.9200,3.9248
185,CA-2018-114321,2018-08-20,Nick Crebassa,Hampton,Furniture,FUR-CH-10001797,500.2400,145.0696
186,CA-2018-114335,2018-09-28,Xylona Preis,Hollywood,Furniture,FUR-FU-10000277,337.0880,16.8544
187,CA-2018-114433,2018-05-13,Naresj Patel,Oakland,Technology,TEC-AC-10002800,149.9700,52.4895
189,CA-2018-114517,2018-12-23,Tiffany House,New York City,Furniture,FUR-TA-10001676,53.3160,-19.5492
192,CA-2018-115049,2018-09-26,Michael Moore,Chicago,Technology,TEC-AC-10004859,153.8240,38.4560
194,CA-2018-115084,2018-10-18,Luke Schmidt,Texarkana,Furniture,FUR-CH-10004626,605.3400,145.2816
196,CA-2018-115161,2018-01-31,Liz Carlisle,Mission Viejo,Furniture,FUR-BO-10003966,290.6660,3.4196
199,CA-2018-115357,2018-08-06,Roland Fjeld,Columbia,Technology,TEC-AC-10000023,62.9100,22.6476
200,CA-2018-115791,2018-01-16,Delfina Latchford,Philadelphia,Furniture,FUR-FU-10001095,127.1040,28.5984
201,CA-2018-115812,2018-06-09,Brosina Hoffman,Los Angeles,Furniture,FUR-FU-10001487,48.8600,14.1694
205,CA-2018-116190,2018-07-26,Sheri Gordon,Atlanta,Furniture,FUR-CH-10000553,67.8800,18.3276
207,CA-2018-116246,2018-09-12,Luke Weiss,New York City,Furniture,FUR-CH-10002024,3785.2920,420.5880
209,CA-2018-116568,2018-12-14,Bryan Mills,Deltona,Furniture,FUR-CH-10002439,186.3040,13.9728
210,CA-2018-116666,2018-05-08,Kean Thornton,Philadelphia,Technology,TEC-CO-10001449,1799.9700,239.9960
211,CA-2018-116673,2018-12-15,Jas O'Carroll,San Diego,Furniture,FUR-FU-10003829,6.1600,1.9712
214,CA-2018-116834,2018-10-11,Dean percer,Seattle,Furniture,FUR-FU-10001196,63.4700,19.0410
216,CA-2018-116932,2018-07-21,Michelle Ellison,San Francisco,Furniture,FUR-CH-10001215,801.5680,50.0980
219,CA-2018-117345,2018-08-01,Barbara Fisher,Charlotte,Furniture,FUR-FU-10000629,44.1280,12.1352
220,CA-2018-117429,2018-10-07,Mathew Reese,Philadelphia,Furniture,FUR-FU-10000222,129.9200,21.1120
221,CA-2018-117464,2018-07-22,Naresj Patel,San Francisco,Furniture,FUR-CH-10000155,717.7200,71.7720
225,CA-2018-117765,2018-09-07,Rick Bensley,Tulsa,Furniture,FUR-CH-10004698,161.9600,45.3488
227,CA-2018-118276,2018-12-29,Michael Granlund,Saint Charles,Furniture,FUR-FU-10002111,8.7360,-4.8048
228,CA-2018-118304,2018-04-29,Katherine Hughes,Dover,Technology,TEC-PH-10000376,19.9800,5.1948
230,CA-2018-118962,2018-08-05,Chad Sievert,Los Angeles,Furniture,FUR-CH-10003817,340.1440,21.2590
233,CA-2018-119144,2018-11-16,Justin Deggeller,Los Angeles,Furniture,FUR-BO-10004015,305.9745,25.1979
234,CA-2018-119151,2018-11-25,Mike Pelletier,New York City,Furniture,FUR-BO-10003159,275.9520,-37.9434
236,CA-2018-119375,2018-11-17,Yoseph Carroll,Newark,Furniture,FUR-FU-10002379,124.4100,14.9292
237,CA-2018-119466,2018-12-15,Sung Pak,Chicago,Furniture,FUR-FU-10001546,8.5440,-7.4760
243,CA-2018-120411,2018-09-20,Sarah Brown,Chicago,Furniture,FUR-BO-10004218,493.4300,-70.4900
245,CA-2018-120474,2018-12-01,Resi Pölking,Madison,Furniture,FUR-CH-10001854,2807.8400,673.8816
246,CA-2018-120544,2018-11-23,Saphhira Shifley,Mesquite,Furniture,FUR-FU-10001940,6.3680,-2.5472
247,CA-2018-120670,2018-11-02,Julie Kriz,Fort Lauderdale,Technology,TEC-AC-10004171,799.9200,239.9760
248,CA-2018-120768,2018-12-19,Irene Maddox,Florence,Furniture,FUR-CH-10000513,1819.8600,163.7874
249,CA-2018-120775,2018-10-03,Russell D'Ascenzo,Dallas,Furniture,FUR-FU-10000758,31.7760,-19.0656
252,CA-2018-120887,2018-09-27,Thomas Seio,Hackensack,Furniture,FUR-FU-10001588,87.5400,37.6422
254,CA-2018-121006,2018-11-10,Sam Craven,Midland,Furniture,FUR-CH-10004997,563.9400,112.7880
258,CA-2018-121629,2018-11-28,Brian Thompson,Houston,Technology,TEC-MA-10004679,998.8500,-199.7700
262,CA-2018-121769,2018-04-08,John Stevenson,Toledo,Furniture,FUR-TA-10004442,172.1100,-94.6605
264,CA-2018-122217,2018-11-24,Harold Pawlan,Virginia Beach,Furniture,FUR-FU-10002045,111.1500,48.9060
267,CA-2018-122588,2018-11-25,Andy Reiter,Woonsocket,Furniture,FUR-FU-10001095,52.9600,20.1248
268,CA-2018-122609,2018-11-12,Darren Powers,Carrollton,Furniture,FUR-FU-10004587,25.1280,-6.9102
270,CA-2018-122749,2018-12-03,Nathan Gelder,Oklahoma City,Technology,TEC-PH-10003811,479.9600,134.3888
271,CA-2018-122882,2018-09-07,Sean Braxton,Philadelphia,Furniture,FUR-FU-10000758,42.3680,8.4736
272,CA-2018-122931,2018-09-29,Suzanne McNair,Philadelphia,Furniture,FUR-TA-10004147,67.1760,-20.1528
277,CA-2018-123260,2018-08-26,Frank Merwin,Los Angeles,Technology,TEC-AC-10002323,176.8000,22.9840
278,CA-2018-123295,2018-07-18,Adrian Hane,Tucson,Furniture,FUR-CH-10002372,259.1360,-25.9136
285,CA-2018-123855,2018-06-18,Mick Crebagga,Los Angeles,Technology,TEC-PH-10000215,139.8000,12.2325
287,CA-2018-124023,2018-04-07,Pauline Johnson,Mobile,Furniture,FUR-FU-10004415,8.9600,2.7776
288,CA-2018-124079,2018-12-13,Randy Ferguson,Phoenix,Furniture,FUR-FU-10002553,87.9600,7.6965
289,CA-2018-124247,2018-12-16,Stefanie Holloman,Sacramento,Furniture,FUR-CH-10001854,1403.9200,70.1960
291,CA-2018-124429,2018-05-27,Maya Herman,San Diego,Furniture,FUR-TA-10002607,567.1200,-28.3560
293,CA-2018-124478,2018-08-08,Matt Abelman,Trenton,Furniture,FUR-FU-10002088,53.8800,22.6296
295,CA-2018-124618,2018-05-02,Cari Schnelling,Lakeland,Technology,TEC-CO-10004202,479.9840,89.9970
297,CA-2018-124688,2018-08-27,Corey Catlett,Springfield,Furniture,FUR-FU-10002456,29.1200,12.5216
298,CA-2018-124702,2018-11-18,Maya Herman,Seattle,Furniture,FUR-FU-10003553,137.5400,55.0160
299,CA-2018-124709,2018-07-27,Giulietta Weimer,San Francisco,Technology,TEC-AC-10002842,238.0000,38.0800
300,CA-2018-124723,2018-08-05,Gary Zandusky,Texas City,Furniture,FUR-TA-10001307,489.2300,41.9340
302,CA-2018-124737,2018-08-23,Arthur Prichep,Denver,Furniture,FUR-FU-10003274,4.2240,1.2672
304,CA-2018-124856,2018-09-29,Lisa DeCherney,New York City,Furniture,FUR-FU-10000521,117.3600,36.3816
306,CA-2018-125150,2018-05-16,Pauline Webber,Los Angeles,Furniture,FUR-CH-10002439,232.8800,17.4660
313,CA-2018-125731,2018-09-10,Clay Ludtke,Gresham,Furniture,FUR-CH-10003973,1487.0400,148.7040
314,CA-2018-125759,2018-02-08,Nathan Mautz,North Las Vegas,Furniture,FUR-FU-10002111,14.5600,5.5328
315,CA-2018-125829,2018-11-04,William Brown,Los Angeles,Furniture,FUR-TA-10002041,573.7280,-64.5444
316,CA-2018-125997,2018-09-20,Mitch Webber,New York City,Furniture,FUR-BO-10002213,801.5680,-10.0196
317,CA-2018-126032,2018-06-23,Brian Stugart,Philadelphia,Technology,TEC-AC-10000158,86.3760,1.0797
323,CA-2018-126403,2018-09-09,Rick Reed,Lowell,Furniture,FUR-CH-10003761,785.8800,212.1876
326,CA-2018-126683,2018-09-29,Paul Prost,Seattle,Furniture,FUR-FU-10001706,6.1600,2.9568
327,CA-2018-126760,2018-07-26,Kunst Miller,North Las Vegas,Furniture,FUR-CH-10003312,674.3520,-109.5822
328,CA-2018-126802,2018-12-29,Zuschuss Carroll,Chicago,Furniture,FUR-FU-10000193,38.9760,-50.6688
331,CA-2018-127012,2018-08-11,Greg Matthias,Seattle,Furniture,FUR-FU-10003691,12.3500,5.4340
333,CA-2018-127159,2018-05-12,Hunter Lopez,Milwaukee,Furniture,FUR-FU-10000010,34.7900,10.7849
334,CA-2018-127166,2018-05-21,Katherine Hughes,Houston,Furniture,FUR-CH-10003396,107.7720,-29.2524
335,CA-2018-127187,2018-12-04,Cathy Prescott,New York City,Technology,TEC-PH-10000673,129.9800,62.3904
338,CA-2018-127446,2018-11-25,Matt Collister,Arlington,Furniture,FUR-FU-10000221,6.0960,-3.9624
341,CA-2018-127558,2018-11-15,Shahid Shariari,Los Angeles,Furniture,FUR-FU-10002505,10.1100,3.2352
343,CA-2018-127614,2018-02-11,Natalie Fritzler,Chesapeake,Furniture,FUR-TA-10003715,1256.2200,75.3732
352,CA-2018-128209,2018-11-17,Greg Tran,Buffalo,Furniture,FUR-BO-10002213,4007.8400,-50.0980
364,CA-2018-129189,2018-07-21,Harry Marie,Dallas,Furniture,FUR-CH-10004997,657.9300,-93.9900
368,CA-2018-129924,2018-07-12,Alyssa Crouse,San Francisco,Furniture,FUR-TA-10004575,698.3520,-17.4588
369,CA-2018-129938,2018-12-15,Ed Braxton,Philadelphia,Furniture,FUR-CH-10003774,445.8020,-108.2662
370,CA-2018-130092,2018-01-11,Seth Vernon,Dover,Furniture,FUR-FU-10000010,9.9400,3.0814
374,CA-2018-130428,2018-03-31,Trudy Glocke,Tampa,Furniture,FUR-CH-10002965,1125.4880,98.4802
375,CA-2018-130449,2018-09-06,Victoria Pisteka,San Francisco,Furniture,FUR-FU-10001487,41.8800,12.1452
378,CA-2018-130673,2018-05-20,Matt Collister,San Marcos,Furniture,FUR-FU-10003489,10.3320,-5.9409
384,CA-2018-131002,2018-09-07,Tom Boeckenhauer,Tulsa,Furniture,FUR-FU-10004270,57.6900,23.6529
385,CA-2018-131009,2018-03-01,Shahid Collister,El Paso,Furniture,FUR-CH-10001270,362.2500,0.0000
386,CA-2018-131051,2018-12-01,Toby Ritter,San Francisco,Furniture,FUR-FU-10001861,58.2000,28.5180
387,CA-2018-131247,2018-03-30,Guy Armstrong,San Francisco,Furniture,FUR-BO-10001337,205.6660,-12.0980
388,CA-2018-131310,2018-07-12,Clay Ludtke,Seattle,Furniture,FUR-CH-10001797,123.1360,13.8528
389,CA-2018-131387,2018-04-28,Arianne Irving,San Francisco,Technology,TEC-PH-10001459,1679.9600,125.9970
390,CA-2018-131450,2018-08-08,Lena Radford,San Diego,Furniture,FUR-FU-10001979,327.7600,91.7728
391,CA-2018-131527,2018-12-01,Toby Braunhardt,Jacksonville,Technology,TEC-PH-10001644,95.9680,9.5968
392,CA-2018-131541,2018-07-28,Chloris Kastensmidt,Apopka,Furniture,FUR-FU-10003623,129.8880,12.9888
395,CA-2018-131926,2018-06-01,Dianna Wilson,Lakeville,Furniture,FUR-CH-10004063,2001.8600,580.5394
399,CA-2018-132451,2018-09-26,Karen Ferguson,San Diego,Furniture,FUR-CH-10000454,585.5520,73.1940
400,CA-2018-132500,2018-09-08,Gary Zandusky,San Francisco,Technology,TEC-AC-10001383,49.9800,8.4966
402,CA-2018-132612,2018-06-09,Frank Olsen,Harrisonburg,Furniture,FUR-TA-10004534,1441.3000,245.0210
405,CA-2018-132864,2018-12-02,Katherine Nockton,Columbus,Technology,TEC-AC-10001267,119.8000,29.9500
408,CA-2018-132983,2018-04-28,David Smith,Jamestown,Technology,TEC-AC-10000736,159.9800,57.5928
409,CA-2018-133158,2018-08-19,David Wiener,Los Angeles,Furniture,FUR-FU-10000723,289.2400,26.0316
410,CA-2018-133228,2018-04-04,Maurice Satty,Detroit,Furniture,FUR-FU-10004020,5.4700,2.3521
417,CA-2018-133592,2018-12-31,Katherine Murray,Providence,Furniture,FUR-BO-10000362,341.9600,78.6508
418,CA-2018-133634,2018-11-05,Steven Roelle,Arlington,Technology,TEC-AC-10002550,47.7900,16.2486
419,CA-2018-133690,2018-08-03,Bruce Stewart,Denver,Furniture,FUR-TA-10004289,218.7500,-161.8750
426,CA-2018-134061,2018-04-29,Lauren Leatherbury,Rochester,Furniture,FUR-FU-10001424,17.4600,5.9364
429,CA-2018-134278,2018-07-06,Emily Phan,New York City,Technology,TEC-CO-10001046,559.9920,174.9975
431,CA-2018-134551,2018-12-20,Tony Sayre,Columbia,Furniture,FUR-CH-10004287,662.8800,74.5740
432,CA-2018-134572,2018-04-20,Seth Vernon,Houston,Furniture,FUR-TA-10001705,744.1000,-95.6700
434,CA-2018-134677,2018-10-06,Xylona Preis,San Diego,Technology,TEC-AC-10001445,9.0900,1.9089
435,CA-2018-134726,2018-11-02,Steven Ward,Seattle,Technology,TEC-AC-10000023,41.9400,15.0984
438,CA-2018-135608,2018-12-08,Jim Karlsson,Olympia,Furniture,FUR-CH-10002602,603.9200,45.2940
439,CA-2018-135657,2018-06-03,Steven Cartwright,Seattle,Furniture,FUR-TA-10004086,515.8800,113.4936
442,CA-2018-135993,2018-05-28,Patrick Jones,Seattle,Technology,TEC-AC-10004877,27.6000,2.2080
445,CA-2018-136399,2018-12-16,Chad Cunningham,Los Angeles,Furniture,FUR-CH-10002602,241.5680,18.1176
446,CA-2018-136567,2018-12-20,Penelope Sewall,Harrisonburg,Furniture,FUR-TA-10000617,455.1000,100.1220
447,CA-2018-136644,2018-06-16,Sonia Cooley,Mishawaka,Furniture,FUR-CH-10000225,647.8400,32.3920
449,CA-2018-136861,2018-09-05,Patrick Ryan,Saint Petersburg,Furniture,FUR-FU-10001967,31.9840,1.9990
451,CA-2018-137274,2018-03-29,Mike Gockenbach,Plano,Furniture,FUR-TA-10001889,890.8410,-152.7156
453,CA-2018-137575,2018-08-06,Trudy Brown,New York City,Technology,TEC-AC-10004571,199.9800,83.9916
457,CA-2018-138072,2018-12-30,Guy Armstrong,Philadelphia,Technology,TEC-AC-10004859,27.9680,6.9920
458,CA-2018-138100,2018-09-15,Alex Avila,New York City,Furniture,FUR-FU-10002456,14.5600,6.2608
460,CA-2018-138177,2018-09-19,Neil Ducich,Chandler,Furniture,FUR-TA-10004607,73.9150,-45.8273
464,CA-2018-138317,2018-06-21,Natalie Webber,Philadelphia,Furniture,FUR-FU-10000550,3.9840,0.6474
466,CA-2018-138436,2018-03-26,Jonathan Doherty,Los Angeles,Technology,TEC-AC-10002323,66.3000,8.6190

In [48]:
fc2=df['category'].isin(cat) & (df['customer_name'] == 'Laurel Elliston')
df[fc2]

,order_id,order_date,customer_name,city,category,product_id,sales,profit
7,CA-2018-100706,2018-12-16,Laurel Elliston,Springfield,Furniture,FUR-FU-10002268,29.460,9.7218
2582,CA-2020-157245,2020-05-19,Laurel Elliston,Arlington,Furniture,FUR-CH-10003746,641.960,179.7488
2990,CA-2021-108329,2021-12-09,Laurel Elliston,Whittier,Technology,TEC-PH-10001918,444.768,44.4768
4938,US-2021-150595,2021-05-22,Laurel Elliston,Chicago,Furniture,FUR-CH-10000513,181.986,-54.5958